import type { Restaurant } from "./types";

/**
 * Curated database of common US chains and their gluten-free reality.
 *
 * `baseGrade` = best-case grade for a RELAXED (ingredients-only) eater.
 * The grading engine (lib/grading.ts) then adjusts per user profile:
 *   - `dedicatedFryer`: true = no shared-fryer / shared hot-surface risk
 *   - `crossContaminationProtocol`: true = documented allergen handling / clean prep
 *   - `hasGfMenu`: publishes a gluten-free or allergen menu
 *
 * So a place with a GF bun but a shared fryer is an A for someone cutting back
 * and a D for someone with celiac — same data, different grade per person.
 *
 * Accuracy note: gluten-free offerings change and vary by location/franchise.
 * Always confirm with staff. Data reflects well-documented GF community guidance.
 */
export const SEED_RESTAURANTS: Restaurant[] = [
  // ───────────────────────── FAST FOOD · BURGERS ─────────────────────────
  {
    id: "innout",
    name: "In-N-Out",
    domain: "in-n-out.com",
    segment: "fast-food",
    category: "Burgers",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: false,
    summary:
      "A surprise standout. Order any burger 'Protein Style' (lettuce wrap) and the fries are fresh-cut potatoes cooked in a dedicated fryer with nothing breaded.",
    menu: [
      { name: "Burger 'Protein Style'", status: "gf-modifiable", note: "Lettuce wrap instead of a bun." },
      { name: "Fries", status: "naturally-gf", note: "Dedicated fryer, just potatoes & oil." },
      { name: "Shakes", status: "naturally-gf" },
      { name: "Regular bun", status: "risky" },
    ],
    orderingTips: [
      "Say 'Protein Style' for a lettuce-wrapped burger.",
      "Fries here are genuinely safe — dedicated oil, no breaded items.",
      "Mention the allergy so they change gloves.",
    ],
  },
  {
    id: "fiveguys",
    name: "Five Guys",
    domain: "fiveguys.com",
    segment: "fast-food",
    category: "Burgers",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Fries are cooked in 100% peanut oil with nothing breaded, and a bunless burger is easy. The flat-top grill is shared with buns, so there's some surface risk.",
    menu: [
      { name: "Bunless burger (bowl/lettuce)", status: "gf-modifiable" },
      { name: "Fries", status: "naturally-gf", note: "Dedicated peanut-oil fryer, only potatoes." },
      { name: "Hot dog, no bun", status: "gf-modifiable" },
      { name: "Bun / toasted items", status: "risky" },
    ],
    orderingTips: [
      "Order it 'in a bowl' or as a lettuce wrap and ask for a glove change.",
      "Fries are a safe bet here thanks to the dedicated fryer.",
      "Ask them to grill your patty on a clean spot away from buns.",
    ],
  },
  {
    id: "culvers",
    name: "Culver's",
    domain: "culvers.com",
    segment: "fast-food",
    category: "Burgers / Frozen custard",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Has a published gluten-free guide and a gluten-free bun. Fries and cheese curds share a fryer with breaded items, so fried food is off-limits if you react to cross-contact.",
    menu: [
      { name: "ButterBurger on GF bun", status: "gf-menu-item", note: "Ask for the gluten-free bun." },
      { name: "Burger patty (lettuce wrap)", status: "gf-modifiable" },
      { name: "Most frozen custard", status: "gf-modifiable", note: "Avoid cookie/brownie mix-ins." },
      { name: "Fries / cheese curds", status: "risky", note: "Shared fryer." },
    ],
    orderingTips: [
      "Ask for the gluten-free bun and a glove change.",
      "Swap fries for a side salad or steamed veg.",
      "For custard, choose plain or fruit mix-ins.",
    ],
  },
  {
    id: "shakeshack",
    name: "Shake Shack",
    domain: "shakeshack.com",
    segment: "fast-food",
    category: "Burgers",
    baseGrade: "B",
    dedicatedFryer: true,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Offers gluten-free buns and the crinkle-cut fries are cooked in a dedicated fryer. The griddle is shared, so a glove change and clean spot help.",
    menu: [
      { name: "ShackBurger on GF bun", status: "gf-menu-item" },
      { name: "Fries", status: "naturally-gf", note: "Dedicated fryer." },
      { name: "Most concretes / shakes", status: "gf-modifiable" },
      { name: "Chicken / 'Shroom (breaded)", status: "risky" },
    ],
    orderingTips: [
      "Ask for the gluten-free bun (sealed/separate).",
      "Fries are cooked separately — usually safe.",
      "Request a glove change and clean griddle area.",
    ],
  },
  {
    id: "whataburger",
    name: "Whataburger",
    domain: "whataburger.com",
    segment: "fast-food",
    category: "Burgers",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Has a gluten-free bun and an allergen guide. Fries share a fryer with breaded items, so skip them if cross-contact is an issue.",
    menu: [
      { name: "Burger on GF bun", status: "gf-menu-item" },
      { name: "Patty in a lettuce wrap", status: "gf-modifiable" },
      { name: "Fries", status: "risky", note: "Shared fryer." },
    ],
    orderingTips: [
      "Request the gluten-free bun and a glove change.",
      "Skip fries; ask for apple slices or a side instead.",
    ],
  },
  {
    id: "wendys",
    name: "Wendy's",
    domain: "wendys.com",
    segment: "fast-food",
    category: "Burgers",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "No GF bun and a shared fryer, but a baked potato and chili give you real, non-fried options.",
    menu: [
      { name: "Plain baked potato", status: "naturally-gf" },
      { name: "Chili", status: "naturally-gf", note: "Verify current recipe." },
      { name: "Burger patty, no bun", status: "gf-modifiable" },
      { name: "Fries / nuggets", status: "risky" },
    ],
    orderingTips: [
      "Baked potato + chili is a solid non-fried meal.",
      "Skip fries (shared fryer); patty without the bun works.",
    ],
  },
  {
    id: "mcdonalds",
    name: "McDonald's",
    domain: "mcdonalds.com",
    segment: "fast-food",
    category: "Burgers",
    baseGrade: "D",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "No gluten-free bun in the US and a shared fryer for everything. Slim pickings — mostly a bunless patty or a salad.",
    menu: [
      { name: "Burger patty, no bun", status: "gf-modifiable" },
      { name: "Side salad (no croutons)", status: "naturally-gf" },
      { name: "Fries", status: "risky", note: "Shared fryer + flavoring concerns." },
      { name: "Any sandwich / McNuggets", status: "risky" },
    ],
    orderingTips: [
      "A plain patty is about it — there's no GF bun.",
      "Fries are not safe for cross-contamination.",
      "Better chains usually exist nearby; use in a pinch.",
    ],
  },
  {
    id: "burgerking",
    name: "Burger King",
    domain: "bk.com",
    segment: "fast-food",
    category: "Burgers",
    baseGrade: "D",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "No GF bun and a shared fryer. A flame-grilled patty without the bun or a garden side salad are your only real options.",
    menu: [
      { name: "Flame-grilled patty, no bun", status: "gf-modifiable" },
      { name: "Garden side salad (no croutons)", status: "naturally-gf" },
      { name: "Fries / onion rings", status: "risky" },
    ],
    orderingTips: [
      "Order a bunless patty and confirm no shared toppings.",
      "Avoid all fried items — shared fryer.",
    ],
  },
  {
    id: "sonic",
    name: "Sonic Drive-In",
    domain: "sonicdrivein.com",
    segment: "fast-food",
    category: "Burgers / Drive-in",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Has an allergen guide but a shared fryer and no GF bun. Bunless burgers, hot dogs without the bun, and many drinks/slushes work.",
    menu: [
      { name: "Burger patty, no bun", status: "gf-modifiable" },
      { name: "Most slushes & shakes", status: "gf-modifiable" },
      { name: "Tots / fries / anything fried", status: "risky" },
    ],
    orderingTips: [
      "Go bunless and skip the fried sides.",
      "Check the allergen guide for current shake mix-ins.",
    ],
  },
  {
    id: "dairyqueen",
    name: "Dairy Queen",
    domain: "dairyqueen.com",
    segment: "fast-food",
    category: "Burgers / Ice cream",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Soft-serve and many Blizzards (with GF mix-ins) are fine, and a bunless burger works. Everything fried shares oil.",
    menu: [
      { name: "Plain soft-serve / cone base", status: "gf-modifiable" },
      { name: "Blizzard with GF mix-ins", status: "gf-modifiable", note: "Avoid cookie dough / brownie." },
      { name: "Burger patty, no bun", status: "gf-modifiable" },
      { name: "Fries / chicken strips", status: "risky" },
    ],
    orderingTips: [
      "Pick fruit or candy Blizzard mix-ins, not cookie-based.",
      "Skip fried sides — shared fryer.",
    ],
  },

  // ───────────────────────── FAST FOOD · CHICKEN ─────────────────────────
  {
    id: "chickfila",
    name: "Chick-fil-A",
    domain: "chick-fil-a.com",
    segment: "fast-food",
    category: "Chicken",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "One of the most celiac-friendly fast-food chains: a sealed gluten-free bun, grilled nuggets/filets, and waffle fries cooked in a dedicated canola fryer.",
    menu: [
      { name: "Grilled nuggets / filet", status: "naturally-gf" },
      { name: "Gluten-free bun (packaged)", status: "gf-menu-item" },
      { name: "Waffle fries", status: "naturally-gf", note: "Dedicated fryer." },
      { name: "Breaded chicken / breakfast biscuits", status: "risky" },
    ],
    orderingTips: [
      "Get grilled (not breaded) nuggets or filet and the sealed GF bun.",
      "Waffle fries are cooked in a dedicated fryer — usually safe.",
      "Ask for a glove change when they plate it.",
    ],
  },
  {
    id: "kfc",
    name: "KFC",
    domain: "kfc.com",
    segment: "fast-food",
    category: "Fried chicken",
    baseGrade: "F",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Built around breaded fried chicken with shared oil. Almost nothing is safe beyond a couple of plain sides.",
    menu: [
      { name: "Green beans / corn (verify)", status: "gf-modifiable" },
      { name: "Mashed potatoes (no gravy)", status: "gf-modifiable", note: "Gravy contains wheat." },
      { name: "All chicken / biscuits", status: "risky" },
    ],
    orderingTips: [
      "Realistically not a safe choice — fried, breaded everything.",
      "At most, a plain side; verify with the allergen guide.",
    ],
  },
  {
    id: "popeyes",
    name: "Popeyes",
    domain: "popeyes.com",
    segment: "fast-food",
    category: "Fried chicken",
    baseGrade: "F",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Like KFC — breaded, fried, shared oil. Very little is gluten-free and cross-contact is everywhere.",
    menu: [
      { name: "Red beans & rice (verify)", status: "gf-modifiable" },
      { name: "All chicken / biscuits / fries", status: "risky" },
    ],
    orderingTips: ["Best avoided if you react to cross-contact."],
  },
  {
    id: "raisingcanes",
    name: "Raising Cane's",
    domain: "raisingcanes.com",
    segment: "fast-food",
    category: "Chicken fingers",
    baseGrade: "F",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "The whole menu is breaded chicken fingers, fries, and Texas toast — all gluten or shared fryer. Effectively nothing safe.",
    menu: [
      { name: "Coleslaw (verify)", status: "gf-modifiable" },
      { name: "Chicken fingers / fries / toast", status: "risky" },
    ],
    orderingTips: ["Not a workable option for gluten-free eating."],
  },
  {
    id: "wingstop",
    name: "Wingstop",
    domain: "wingstop.com",
    segment: "fast-food",
    category: "Wings",
    baseGrade: "F",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Classic (bone-in) wings are naturally gluten-free, but they're fried in shared oil with breaded boneless wings and fries.",
    menu: [
      { name: "Classic wings + GF-safe rub", status: "risky", note: "Shared fryer with breaded items." },
      { name: "Fries / boneless / corn (cooked w/ wheat)", status: "risky" },
    ],
    orderingTips: [
      "Only realistic if you tolerate a shared fryer — then classic wings with a dry rub.",
      "Confirm the seasoning/sauce is gluten-free.",
    ],
  },

  // ───────────────────── FAST CASUAL · MEXICAN / BOWLS ────────────────────
  {
    id: "chipotle",
    name: "Chipotle",
    domain: "chipotle.com",
    segment: "fast-casual",
    category: "Mexican",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "One of the safest fast options. No fryer at all, and staff change gloves on request. Everything except the flour tortilla is gluten-free.",
    menu: [
      { name: "Burrito bowl", status: "naturally-gf", note: "Skip the flour tortilla." },
      { name: "Corn tortillas / tacos", status: "naturally-gf" },
      { name: "All meats, rice, beans, salsas, guac", status: "naturally-gf" },
      { name: "Flour tortilla / quesadilla", status: "risky" },
    ],
    orderingTips: [
      "Ask for a fresh-gloves change before they build your bowl.",
      "Order a bowl, not a burrito — chips are gluten-free too.",
      "If the line looks messy, ask them to grab from the back.",
    ],
  },
  {
    id: "qdoba",
    name: "Qdoba",
    domain: "qdoba.com",
    segment: "fast-casual",
    category: "Mexican",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Very similar to Chipotle: no fryer, an allergen guide, and a build-your-own bowl that's almost entirely gluten-free.",
    menu: [
      { name: "Build-your-own bowl", status: "naturally-gf" },
      { name: "Corn tortillas", status: "naturally-gf" },
      { name: "Meats, beans, rice, salsas, queso", status: "naturally-gf" },
      { name: "Flour tortilla", status: "risky" },
    ],
    orderingTips: [
      "Go for a bowl and request a glove change.",
      "Tortilla chips are corn-based and usually gluten-free.",
    ],
  },
  {
    id: "moes",
    name: "Moe's Southwest Grill",
    domain: "moes.com",
    segment: "fast-casual",
    category: "Mexican",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Build-your-own bowls with no fryer and an allergen guide. Skip the flour tortilla and most everything else is gluten-free.",
    menu: [
      { name: "Burrito bowl", status: "naturally-gf" },
      { name: "Meats, rice, beans, salsas, queso", status: "naturally-gf" },
      { name: "Flour tortilla", status: "risky" },
    ],
    orderingTips: [
      "Order a bowl and ask for fresh gloves.",
      "Chips are corn — usually fine; confirm locally.",
    ],
  },
  {
    id: "cava",
    name: "CAVA",
    domain: "cava.com",
    segment: "fast-casual",
    category: "Mediterranean",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Mediterranean bowls are largely naturally gluten-free — only the pita and a couple of dressings contain gluten. No fryer on the line.",
    menu: [
      { name: "Grain or salad bowl", status: "naturally-gf", note: "Skip the pita." },
      { name: "Proteins, dips, veggies", status: "naturally-gf" },
      { name: "Pita / pita chips", status: "risky" },
    ],
    orderingTips: [
      "Build a bowl (no pita) and ask for a glove change.",
      "Check that your chosen dressing is gluten-free.",
    ],
  },
  {
    id: "sweetgreen",
    name: "Sweetgreen",
    domain: "sweetgreen.com",
    segment: "fast-casual",
    category: "Salads / Bowls",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Salad and warm bowls with clear allergen labeling and no fryer. Most ingredients are naturally gluten-free; a few dressings and crispy toppings aren't.",
    menu: [
      { name: "Custom salad / warm bowl", status: "naturally-gf" },
      { name: "Proteins, grains, veggies", status: "naturally-gf" },
      { name: "Crispy onions / some dressings", status: "risky", note: "Check labels." },
    ],
    orderingTips: [
      "Use the in-app allergen filter to mark gluten-free.",
      "Skip crispy/fried toppings and verify the dressing.",
    ],
  },
  {
    id: "tacobell",
    name: "Taco Bell",
    domain: "tacobell.com",
    segment: "fast-food",
    category: "Mexican",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Publishes ingredient info and has options (Power Menu Bowl), but there's no GF certification, shared prep, and a shared fryer.",
    menu: [
      { name: "Power Menu Bowl (no tortilla strips)", status: "gf-modifiable" },
      { name: "Crunchy taco (corn, verify)", status: "gf-modifiable" },
      { name: "Anything with flour tortilla / fried", status: "risky" },
    ],
    orderingTips: [
      "A Power Bowl without strips is the safest bet; expect some cross-contact.",
      "Use the online allergen tool to build a meal.",
    ],
  },
  {
    id: "deltaco",
    name: "Del Taco",
    domain: "deltaco.com",
    segment: "fast-food",
    category: "Mexican",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Some corn-tortilla and bowl options work, but there's a shared fryer and shared prep, and no dedicated GF menu.",
    menu: [
      { name: "Taco on corn tortilla (verify)", status: "gf-modifiable" },
      { name: "Rice & beans bowl", status: "gf-modifiable" },
      { name: "Fries / shells / flour items", status: "risky" },
    ],
    orderingTips: [
      "Stick to corn-tortilla or bowl items and ask for fresh gloves.",
      "Skip the fried sides.",
    ],
  },

  // ───────────────────────── FAST FOOD · SANDWICHES ─────────────────────────
  {
    id: "jerseymikes",
    name: "Jersey Mike's",
    domain: "jerseymikes.com",
    segment: "fast-food",
    category: "Subs",
    baseGrade: "B",
    dedicatedFryer: true,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Offers gluten-free bread and a 'sub in a tub' (bowl) option, and they'll change gloves and clean the slicer area on request. Flour-dusted shop means some risk.",
    menu: [
      { name: "Sub in a tub (bowl, no bread)", status: "gf-modifiable" },
      { name: "Gluten-free bread sub", status: "gf-menu-item" },
      { name: "Cold cuts & cheeses", status: "naturally-gf" },
      { name: "Regular rolls / anything sliced w/ bread", status: "risky" },
    ],
    orderingTips: [
      "Ask for a 'sub in a tub' or GF bread plus a glove change.",
      "Request a freshly cleaned prep area away from the bread.",
    ],
  },
  {
    id: "jimmyjohns",
    name: "Jimmy John's",
    domain: "jimmyjohns.com",
    segment: "fast-food",
    category: "Subs",
    baseGrade: "B",
    dedicatedFryer: true,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "The 'Unwich' wraps any sub in lettuce instead of bread. No fryer, but the shop is full of bread flour, so cross-contact is possible.",
    menu: [
      { name: "Unwich (lettuce-wrapped)", status: "gf-modifiable" },
      { name: "Meats, cheese, veggies", status: "naturally-gf" },
      { name: "Bread / day-bread items", status: "risky" },
    ],
    orderingTips: [
      "Order any sandwich as an 'Unwich' and ask for a glove change.",
      "Ask them to build it on a clean surface.",
    ],
  },
  {
    id: "firehousesubs",
    name: "Firehouse Subs",
    domain: "firehousesubs.com",
    segment: "fast-food",
    category: "Subs",
    baseGrade: "B",
    dedicatedFryer: true,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Offers a gluten-free sub roll and a salad option. Steamed-meat prep and a bread-heavy shop mean cross-contact is possible.",
    menu: [
      { name: "Sub on GF roll", status: "gf-menu-item" },
      { name: "Salad (no croutons)", status: "gf-modifiable" },
      { name: "Regular rolls", status: "risky" },
    ],
    orderingTips: [
      "Ask for the gluten-free roll and a glove change.",
      "Confirm the meat steamer/prep won't share with bread.",
    ],
  },
  {
    id: "arbys",
    name: "Arby's",
    domain: "arbys.com",
    segment: "fast-food",
    category: "Sandwiches",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Famous for sliced meats, but there's no GF bun, the curly fries share a fryer, and most items are bread-based. A meat-and-toppings plate is about it.",
    menu: [
      { name: "Roast meats (no bun)", status: "gf-modifiable", note: "Confirm no wheat in seasoning." },
      { name: "Chopped side salad", status: "gf-modifiable" },
      { name: "Curly fries / sandwiches", status: "risky" },
    ],
    orderingTips: [
      "Ask for meat without the bun and skip the fries.",
      "Verify the specific meat's ingredients — some are marinated.",
    ],
  },

  // ───────────────────────── FAST · ASIAN / NOODLES ─────────────────────────
  {
    id: "pandaexpress",
    name: "Panda Express",
    domain: "pandaexpress.com",
    segment: "fast-food",
    category: "Chinese",
    baseGrade: "D",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Most dishes use soy sauce (wheat) or are battered/fried, and woks/utensils are shared. Only a couple of items are gluten-free and cross-contact is high.",
    menu: [
      { name: "String bean chicken breast (verify)", status: "gf-modifiable" },
      { name: "Steamed rice / mixed veg", status: "gf-modifiable" },
      { name: "Orange chicken / most entrées", status: "risky" },
    ],
    orderingTips: [
      "Check the allergen list — very few items qualify.",
      "Expect shared woks/serving spoons; risky for celiac.",
    ],
  },
  {
    id: "noodles",
    name: "Noodles & Company",
    domain: "noodles.com",
    segment: "fast-casual",
    category: "Noodles / Pasta",
    baseGrade: "B",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Offers gluten-free fusilli and naturally GF rice noodles, cooked in separate water on request. Has an allergen process and no fryer.",
    menu: [
      { name: "Gluten-free fusilli dishes", status: "gf-menu-item" },
      { name: "Rice-noodle dishes (e.g. Pad Thai)", status: "gf-modifiable" },
      { name: "Zucchini 'zoodles'", status: "gf-modifiable" },
      { name: "Regular wheat noodles", status: "risky" },
    ],
    orderingTips: [
      "Order GF fusilli or rice noodles and ask for fresh pasta water.",
      "Confirm the sauce is gluten-free (some contain soy sauce).",
    ],
  },

  // ───────────────────────── CAFE / BREAKFAST ─────────────────────────
  {
    id: "starbucks",
    name: "Starbucks",
    domain: "starbucks.com",
    segment: "cafe",
    category: "Coffee / Cafe",
    baseGrade: "B",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: false,
    summary:
      "Most drinks are fine, and packaged GF snacks come sealed, which limits cross-contact. Pastries are handled with shared tongs, so stick to sealed items.",
    menu: [
      { name: "Most brewed/espresso drinks", status: "naturally-gf", note: "Skip cookie-crumble toppings." },
      { name: "Packaged GF snacks (sealed)", status: "gf-menu-item" },
      { name: "Egg bites", status: "gf-modifiable", note: "Check current ingredients." },
      { name: "Bakery pastries", status: "risky" },
    ],
    orderingTips: [
      "Choose sealed/packaged snacks rather than case bakery items.",
      "Avoid the cookie-crumble and Frappuccino toppings.",
    ],
  },
  {
    id: "panera",
    name: "Panera Bread",
    domain: "panerabread.com",
    segment: "cafe",
    category: "Bakery / Cafe",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "It's a bakery — airborne flour and shared prep make it tough for celiac. Some soups and salads have no gluten ingredients, but cross-contact is high.",
    menu: [
      { name: "Some soups (verify)", status: "gf-modifiable" },
      { name: "Salads, no croutons", status: "gf-modifiable" },
      { name: "All breads / sandwiches / baked goods", status: "risky" },
    ],
    orderingTips: [
      "Pick a no-gluten-ingredient soup or salad and ask for a glove change.",
      "Be aware the whole bakery has flour in the air — risky for celiac.",
    ],
  },
  {
    id: "dunkin",
    name: "Dunkin'",
    domain: "dunkindonuts.com",
    segment: "cafe",
    category: "Coffee / Donuts",
    baseGrade: "D",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Drinks are mostly fine, but the food is donuts and baked goods everywhere with shared handling. Very little gluten-free food.",
    menu: [
      { name: "Black/plain coffee & espresso", status: "naturally-gf" },
      { name: "Hash browns (verify shared fryer)", status: "risky" },
      { name: "Donuts / bakery / sandwiches", status: "risky" },
    ],
    orderingTips: [
      "Treat it as a drinks stop; skip the food for safety.",
      "Confirm any flavored syrup is gluten-free.",
    ],
  },
  {
    id: "firstwatch",
    name: "First Watch",
    domain: "firstwatch.com",
    segment: "sit-down",
    category: "Breakfast / Brunch",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Daytime brunch spot with strong allergen awareness and a gluten-free guide. Many egg dishes, bowls, and avocado toast on GF bread work well.",
    menu: [
      { name: "Egg dishes / omelets", status: "gf-modifiable" },
      { name: "Power/quinoa bowls", status: "gf-modifiable" },
      { name: "GF toast / English muffin", status: "gf-menu-item" },
      { name: "Pancakes / regular toast", status: "risky" },
    ],
    orderingTips: [
      "Ask for the gluten-free guide and flag celiac to your server.",
      "Request GF bread and a clean pan for eggs.",
    ],
  },

  // ───────────────────────── PIZZA ─────────────────────────
  {
    id: "blazepizza",
    name: "Blaze Pizza",
    domain: "blazepizza.com",
    segment: "fast-casual",
    category: "Pizza",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Offers a gluten-free crust and keto crust, and will change gloves and use a separate prep procedure. The oven is shared, so it's good for sensitivity but riskier for celiac.",
    menu: [
      { name: "Gluten-free crust pizza", status: "gf-menu-item" },
      { name: "Keto crust", status: "gf-menu-item" },
      { name: "Most toppings & sauces", status: "naturally-gf" },
      { name: "Regular dough", status: "risky" },
    ],
    orderingTips: [
      "Ask for the GF crust plus a glove change and clean prep.",
      "Shared oven means some risk — best for non-celiac.",
    ],
  },
  {
    id: "modpizza",
    name: "MOD Pizza",
    domain: "modpizza.com",
    segment: "fast-casual",
    category: "Pizza",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Has a gluten-free crust and a documented allergen process with glove changes. The shared oven still poses some risk for highly sensitive eaters.",
    menu: [
      { name: "Gluten-free crust pizza", status: "gf-menu-item" },
      { name: "Toppings & sauces", status: "naturally-gf" },
      { name: "Regular dough", status: "risky" },
    ],
    orderingTips: [
      "Request the GF crust, fresh gloves, and clean utensils.",
      "Tell them it's an allergy so they follow the protocol.",
    ],
  },
  {
    id: "dominos",
    name: "Domino's",
    domain: "dominos.com",
    segment: "fast-food",
    category: "Pizza",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Sells a gluten-free crust, but Domino's explicitly states it's NOT recommended for celiac — pizzas are prepped in a shared, flour-heavy kitchen.",
    menu: [
      { name: "Gluten-free crust (small)", status: "gf-menu-item", note: "Not celiac-safe per Domino's." },
      { name: "Most toppings & sauces", status: "naturally-gf" },
      { name: "Regular dough / breads / pasta", status: "risky" },
    ],
    orderingTips: [
      "Fine if you're just avoiding gluten ingredients, not for celiac.",
      "Ask for a glove change, but expect shared prep.",
    ],
  },
  {
    id: "pizzahut",
    name: "Pizza Hut",
    domain: "pizzahut.com",
    segment: "fast-food",
    category: "Pizza",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Offers a gluten-free Udi's crust at participating locations, but the shared kitchen means it isn't suitable for celiac.",
    menu: [
      { name: "Gluten-free crust (where offered)", status: "gf-menu-item", note: "Not celiac-safe." },
      { name: "Toppings & sauce", status: "naturally-gf" },
      { name: "Regular crust / pasta / breadsticks", status: "risky" },
    ],
    orderingTips: [
      "Okay for gluten-avoiders; not for celiac due to shared prep.",
      "Confirm your location actually offers the GF crust.",
    ],
  },
  {
    id: "papajohns",
    name: "Papa Johns",
    domain: "papajohns.com",
    segment: "fast-food",
    category: "Pizza",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Has offered a gluten-free crust, but the shared kitchen and flour mean it's positioned for gluten-avoiders, not celiac.",
    menu: [
      { name: "Gluten-free crust (where offered)", status: "gf-menu-item", note: "Not celiac-safe." },
      { name: "Toppings & sauce", status: "naturally-gf" },
      { name: "Regular dough / breadsticks", status: "risky" },
    ],
    orderingTips: [
      "Verify availability at your store first.",
      "Not recommended if you react to cross-contact.",
    ],
  },

  // ───────────────────────── SIT-DOWN · ITALIAN ─────────────────────────
  {
    id: "olivegarden",
    name: "Olive Garden",
    domain: "olivegarden.com",
    segment: "sit-down",
    category: "Italian",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Has a gluten-free menu including GF rotini. Shared kitchen and pasta water add risk, but they'll use a clean pot on request.",
    menu: [
      { name: "GF rotini with marinara", status: "gf-menu-item" },
      { name: "Grilled chicken / salmon", status: "gf-modifiable" },
      { name: "Salad (no croutons), no breadstick", status: "gf-modifiable" },
      { name: "Breadsticks / regular pasta", status: "risky" },
    ],
    orderingTips: [
      "Order from the GF menu and say it's an allergy.",
      "Ask for fresh pasta water and a clean pan.",
      "Ask them not to bring breadsticks (crumbs).",
    ],
  },
  {
    id: "carrabbas",
    name: "Carrabba's Italian Grill",
    domain: "carrabbas.com",
    segment: "sit-down",
    category: "Italian",
    baseGrade: "A",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "One of the best chains for gluten-free Italian: a large dedicated GF menu, GF pasta, and a kitchen well-versed in separate prep.",
    menu: [
      { name: "Gluten-free pasta dishes", status: "gf-menu-item" },
      { name: "Wood-grilled meats & seafood", status: "gf-modifiable" },
      { name: "Many sauces marked GF", status: "gf-menu-item" },
      { name: "Bread / breaded items / fried", status: "risky" },
    ],
    orderingTips: [
      "Ask for the gluten-free menu — it's extensive and clearly marked.",
      "Flag celiac so they use clean water and prep.",
    ],
  },
  {
    id: "cpk",
    name: "California Pizza Kitchen",
    domain: "cpk.com",
    segment: "sit-down",
    category: "Pizza / Italian",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Offers a gluten-free pizza crust with a dedicated prep protocol (separate cutter, gloves) plus GF salads. Shared oven adds some risk for celiac.",
    menu: [
      { name: "Gluten-free crust pizza", status: "gf-menu-item" },
      { name: "Many salads (no croutons)", status: "gf-modifiable" },
      { name: "Regular pizza / pasta", status: "risky" },
    ],
    orderingTips: [
      "Order the GF crust and confirm the dedicated prep steps.",
      "Tell your server it's an allergy, not a preference.",
    ],
  },

  // ───────────────────────── SIT-DOWN · STEAKHOUSE / GRILL ─────────────────────────
  {
    id: "outback",
    name: "Outback Steakhouse",
    domain: "outback.com",
    segment: "sit-down",
    category: "Steakhouse",
    baseGrade: "A",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A well-regarded GF chain with a dedicated gluten-free menu and trained staff. Steaks, seafood, and many sides work — just skip the shared-fryer fries and the Bloomin' Onion.",
    menu: [
      { name: "Steaks (no seasoned butter)", status: "gf-modifiable" },
      { name: "Grilled chicken / salmon", status: "gf-modifiable" },
      { name: "Steamed veg / plain baked potato", status: "naturally-gf" },
      { name: "Fries / Bloomin' Onion / croutons", status: "risky" },
    ],
    orderingTips: [
      "Ask for the gluten-free menu and confirm no glutenous seasoning on the steak.",
      "Skip fries (shared fryer); choose a baked potato or veg.",
    ],
  },
  {
    id: "longhorn",
    name: "LongHorn Steakhouse",
    domain: "longhornsteakhouse.com",
    segment: "sit-down",
    category: "Steakhouse",
    baseGrade: "A",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Steakhouse fare is naturally gluten-friendly and there's a GF menu. Grilled steaks, salads, and plain sides are solid; fried sides share oil.",
    menu: [
      { name: "Grilled steaks & chops", status: "gf-modifiable" },
      { name: "Salads (no croutons)", status: "gf-modifiable" },
      { name: "Baked potato / steamed veg", status: "naturally-gf" },
      { name: "Fries / breaded items", status: "risky" },
    ],
    orderingTips: [
      "Request the GF menu and confirm seasonings.",
      "Pick a baked potato over fries.",
    ],
  },
  {
    id: "texasroadhouse",
    name: "Texas Roadhouse",
    domain: "texasroadhouse.com",
    segment: "sit-down",
    category: "Steakhouse",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Has a gluten-free menu and great steaks, but free rolls and peanuts mean crumbs everywhere and the fryer is shared.",
    menu: [
      { name: "Steaks (plain, no seasoning blend)", status: "gf-modifiable" },
      { name: "Grilled chicken", status: "gf-modifiable" },
      { name: "Baked potato / steamed veg", status: "naturally-gf" },
      { name: "Rolls / fries / Cactus Blossom", status: "risky" },
    ],
    orderingTips: [
      "Ask for the allergen/GF menu and no seasoning if it contains wheat.",
      "Ask them to skip the bucket of rolls at your table.",
    ],
  },
  {
    id: "ruthschris",
    name: "Ruth's Chris Steak House",
    domain: "ruthschris.com",
    segment: "sit-down",
    category: "Steakhouse (upscale)",
    baseGrade: "A",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Upscale steakhouse where most of the menu is naturally gluten-free and the kitchen readily accommodates. Skip the shared-fryer items and bread.",
    menu: [
      { name: "Steaks & seafood", status: "naturally-gf", note: "Ask about the butter/seasoning." },
      { name: "Most vegetable sides", status: "gf-modifiable" },
      { name: "Bread / breaded / fried sides", status: "risky" },
    ],
    orderingTips: [
      "Tell your server you need gluten-free — they're used to it.",
      "Confirm the steak butter and any sauces are gluten-free.",
    ],
  },
  {
    id: "redrobin",
    name: "Red Robin",
    domain: "redrobin.com",
    segment: "sit-down",
    category: "Burgers (casual)",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Offers a gluten-free bun and an allergen menu. Standard fries share a fryer, but they can prepare GF fries in dedicated oil at many locations on request.",
    menu: [
      { name: "Burger on GF bun", status: "gf-menu-item" },
      { name: "Lettuce-wrapped burger", status: "gf-modifiable" },
      { name: "GF fries (request dedicated oil)", status: "gf-modifiable" },
      { name: "Standard fries / onion rings", status: "risky" },
    ],
    orderingTips: [
      "Ask for the GF bun and whether they can do fries in dedicated oil.",
      "Use the allergen menu and flag celiac.",
    ],
  },

  // ───────────────────────── SIT-DOWN · ASIAN ─────────────────────────
  {
    id: "pfchangs",
    name: "P.F. Chang's",
    domain: "pfchangs.com",
    segment: "sit-down",
    category: "Asian",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A gold standard for dining out: a dedicated gluten-free menu, separate prep, gluten-free soy sauce, and clearly marked dishes.",
    menu: [
      { name: "GF menu items (marked)", status: "gf-menu-item" },
      { name: "GF Mongolian beef / chicken", status: "gf-menu-item" },
      { name: "Lettuce wraps (GF version)", status: "gf-modifiable" },
      { name: "Regular soy-based dishes", status: "risky" },
    ],
    orderingTips: [
      "Ask for the gluten-free menu — dishes are clearly marked.",
      "They use separate woks/prep and GF soy sauce for GF orders.",
    ],
  },

  // ───────────────────────── SIT-DOWN · AMERICAN CASUAL ─────────────────────────
  {
    id: "chilis",
    name: "Chili's",
    domain: "chilis.com",
    segment: "sit-down",
    category: "Tex-Mex / American",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Has a gluten-free item list with fajitas, burgers (bunless or GF bun where offered), and salads. The fryer is shared and prep isn't dedicated.",
    menu: [
      { name: "Fajitas (no tortilla)", status: "gf-modifiable" },
      { name: "Burger, bunless or GF bun", status: "gf-modifiable" },
      { name: "Grilled chicken / salads (no croutons)", status: "gf-modifiable" },
      { name: "Chips/fries (shared fryer) / breaded", status: "risky" },
    ],
    orderingTips: [
      "Use the GF list and tell your server it's an allergy.",
      "Skip anything fried; fajitas without the tortilla are reliable.",
    ],
  },
  {
    id: "bjs",
    name: "BJ's Restaurant & Brewhouse",
    domain: "bjsrestaurants.com",
    segment: "sit-down",
    category: "American / Brewhouse",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Has a sizable gluten-free menu including a gluten-free pizza. Good allergen awareness; shared fryer and oven mean fried/baked cross-contact still applies.",
    menu: [
      { name: "Gluten-free pizza", status: "gf-menu-item" },
      { name: "GF menu entrées & salads", status: "gf-menu-item" },
      { name: "Regular pizza / pasta / fried", status: "risky" },
    ],
    orderingTips: [
      "Ask for the gluten-free menu and flag celiac.",
      "Skip fried sides; confirm GF pizza prep steps.",
    ],
  },
  {
    id: "applebees",
    name: "Applebee's",
    domain: "applebees.com",
    segment: "sit-down",
    category: "American casual",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "No dedicated GF menu and a shared fryer, but grilled proteins, steaks, and salads (no croutons) can be ordered gluten-free with care.",
    menu: [
      { name: "Grilled steak / chicken / salmon", status: "gf-modifiable" },
      { name: "Salads (no croutons)", status: "gf-modifiable" },
      { name: "Steamed veg", status: "naturally-gf" },
      { name: "Fries / breaded apps", status: "risky" },
    ],
    orderingTips: [
      "Ask the kitchen to confirm gluten-free for grilled items.",
      "Avoid the fryer; check marinades and sauces.",
    ],
  },
  {
    id: "cheesecakefactory",
    name: "The Cheesecake Factory",
    domain: "thecheesecakefactory.com",
    segment: "sit-down",
    category: "American (large menu)",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Has a 'Gluten Smart' menu (and even GF cheesecake), but the enormous shared kitchen means cross-contact is a real concern for celiac.",
    menu: [
      { name: "Gluten Smart menu items", status: "gf-menu-item" },
      { name: "Gluten-free cheesecake", status: "gf-menu-item" },
      { name: "Grilled proteins & salads", status: "gf-modifiable" },
      { name: "Pasta / bread / fried", status: "risky" },
    ],
    orderingTips: [
      "Ask specifically for the 'Gluten Smart' menu.",
      "Flag celiac — the busy kitchen makes cross-contact likely otherwise.",
    ],
  },
  {
    id: "buffalowildwings",
    name: "Buffalo Wild Wings",
    domain: "buffalowildwings.com",
    segment: "sit-down",
    category: "Wings / Sports bar",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Traditional (bone-in) wings and many sauces are gluten-free by ingredient, but they're fried in shared oil with breaded boneless wings.",
    menu: [
      { name: "Traditional wings + GF sauce", status: "risky", note: "Shared fryer with breaded wings." },
      { name: "Naked tenders (grilled, verify)", status: "gf-modifiable" },
      { name: "Boneless wings / fries", status: "risky" },
    ],
    orderingTips: [
      "Only workable if you tolerate a shared fryer.",
      "Confirm the sauce is gluten-free (many are; some aren't).",
    ],
  },
  {
    id: "redlobster",
    name: "Red Lobster",
    domain: "redlobster.com",
    segment: "sit-down",
    category: "Seafood",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Has a gluten-free menu with steamed/grilled seafood and steak. The famous Cheddar Bay biscuits put crumbs everywhere and fried items share oil.",
    menu: [
      { name: "Steamed/grilled seafood & lobster", status: "gf-modifiable" },
      { name: "Steak / grilled chicken", status: "gf-modifiable" },
      { name: "Plain baked potato / veg", status: "naturally-gf" },
      { name: "Biscuits / fried seafood", status: "risky" },
    ],
    orderingTips: [
      "Ask for the GF menu; choose steamed or grilled, not fried or breaded.",
      "Ask them to keep biscuits away from your plate.",
    ],
  },
  {
    id: "crackerbarrel",
    name: "Cracker Barrel",
    domain: "crackerbarrel.com",
    segment: "sit-down",
    category: "Southern / Comfort",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Lots of the menu is breaded, biscuit-based, or fried, but eggs, grilled meats, and certain plain sides can be eaten gluten-free with care.",
    menu: [
      { name: "Eggs & grilled meats", status: "gf-modifiable" },
      { name: "Plain veg sides (verify)", status: "gf-modifiable" },
      { name: "Biscuits / fried / dumplings", status: "risky" },
    ],
    orderingTips: [
      "Build a breakfast of eggs + grilled meat + GF-safe sides.",
      "Confirm sides aren't dusted with flour or fried.",
    ],
  },
  {
    id: "dennys",
    name: "Denny's",
    domain: "dennys.com",
    segment: "sit-down",
    category: "Diner / Breakfast",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Has allergen guidance and you can build a gluten-free breakfast from eggs, grilled meats, and fruit. Shared grill and fryer add risk.",
    menu: [
      { name: "Eggs, bacon, sausage (verify)", status: "gf-modifiable" },
      { name: "Seasonal fruit", status: "naturally-gf" },
      { name: "Grilled items (no marinade)", status: "gf-modifiable" },
      { name: "Pancakes / hash browns / fried", status: "risky" },
    ],
    orderingTips: [
      "Use the allergen menu to assemble a safe breakfast.",
      "Ask for eggs cooked in a clean pan, not the shared grill.",
    ],
  },

  // ───────────────── SIT-DOWN · STEAKHOUSE / UPSCALE (more) ─────────────────
  {
    id: "fogodechao",
    name: "Fogo de Chão",
    domain: "fogodechao.com",
    segment: "sit-down",
    category: "Brazilian steakhouse",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Roughly 90% naturally gluten-free: the fire-roasted churrasco meats, the Market Table salad bar, and the tapioca-flour cheese bread are all GF by ingredient. One of the safest chain options for GF diners.",
    menu: [
      { name: "Churrasco meats (picanha, filet, lamb)", status: "naturally-gf" },
      { name: "Pão de queijo (cheese bread)", status: "naturally-gf", note: "Made with tapioca flour." },
      { name: "Market Table salad bar", status: "naturally-gf", note: "Skip croutons/bread." },
      { name: "Flan / crème brûlée", status: "naturally-gf" },
    ],
    orderingTips: [
      "Ask for the allergen menu to confirm seasoned/spicy meats.",
      "Avoid croutons and bread on the Market Table.",
      "The core meat + salad bar experience is naturally GF.",
    ],
  },
  {
    id: "texasdebrazil",
    name: "Texas de Brazil",
    domain: "texasdebrazil.com",
    segment: "sit-down",
    category: "Brazilian steakhouse",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Like other churrascarias, the rotating fire-grilled meats, salad area, GF cheese bread, and flan are naturally gluten-free. Staff know which items contain gluten, but there are few formal cross-contact safeguards.",
    menu: [
      { name: "Rotating grilled meats", status: "naturally-gf", note: "Confirm marinated cuts." },
      { name: "Brazilian cheese bread", status: "naturally-gf" },
      { name: "Salad area (build-your-own)", status: "naturally-gf", note: "Avoid croutons/pasta." },
      { name: "Flan / crème brûlée", status: "naturally-gf" },
    ],
    orderingTips: [
      "Tell staff you have celiac and ask which meats to avoid.",
      "Skip croutons, breaded items, and pasta salads on the bar.",
      "Rely on the naturally-GF items rather than a formal protocol.",
    ],
  },
  {
    id: "capitalgrille",
    name: "The Capital Grille",
    domain: "thecapitalgrille.com",
    segment: "sit-down",
    category: "Steakhouse (upscale)",
    baseGrade: "A",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Upscale Darden steakhouse with a printed gluten-sensitive menu mirroring most of the regular menu — steaks, seafood, salads, clam chowder, and GF desserts. Knowledgeable staff; kitchen isn't dedicated GF.",
    menu: [
      { name: "Dry-aged steaks", status: "gf-menu-item" },
      { name: "Grilled seafood", status: "gf-menu-item" },
      { name: "Clam chowder", status: "gf-menu-item" },
      { name: "Crème brûlée / chocolate torte", status: "gf-menu-item" },
      { name: "Salads (no croutons)", status: "gf-modifiable" },
    ],
    orderingTips: [
      "Request the printed gluten-sensitive menu.",
      "Ask the server to flag the kitchen for celiac handling.",
      "Skip the bread service and breaded sides.",
    ],
  },
  {
    id: "flemings",
    name: "Fleming's Prime Steakhouse",
    domain: "flemingssteakhouse.com",
    segment: "sit-down",
    category: "Steakhouse (upscale)",
    baseGrade: "A",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "An extensive GF menu developed with dietitians covering steaks, seafood, salads, sides, and desserts. Staff are well-versed in celiac, though it's a prepared-to-order shared kitchen.",
    menu: [
      { name: "Prime steaks", status: "gf-menu-item" },
      { name: "Grilled seafood", status: "gf-menu-item" },
      { name: "Salads (GF dressings)", status: "gf-menu-item" },
      { name: "GF desserts", status: "gf-menu-item" },
      { name: "Cocktails", status: "naturally-gf" },
    ],
    orderingTips: [
      "Ask for the dedicated GF menu and tell your server.",
      "Skip the bread basket.",
      "Confirm sides and sauces are from the GF list.",
    ],
  },
  {
    id: "seasons52",
    name: "Seasons 52",
    domain: "seasons52.com",
    segment: "sit-down",
    category: "American / Seasonal",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A daily gluten-sensitive menu and — notably — no fryer in the kitchen, eliminating shared-oil risk. Steaks, no-bun burgers, lettuce-wrap tacos, seafood, salads, separately-prepared GF pita, and GF desserts.",
    menu: [
      { name: "Wood-grilled steaks & seafood", status: "gf-menu-item" },
      { name: "GF pita bread", status: "gf-menu-item", note: "Prepared in a separate space." },
      { name: "Lettuce-wrap tacos", status: "gf-modifiable" },
      { name: "Salads", status: "gf-menu-item" },
      { name: "Mini-indulgence desserts", status: "gf-menu-item" },
    ],
    orderingTips: [
      "Ask for the gluten-sensitive specialty menu.",
      "No fryer in-house, so no shared-oil concern.",
      "Request the separately-prepared GF pita.",
    ],
  },
  // ───────────────── FAST CASUAL / HEALTH (more) ─────────────────
  {
    id: "truefoodkitchen",
    name: "True Food Kitchen",
    domain: "truefoodkitchen.com",
    segment: "fast-casual",
    category: "Health / American",
    baseGrade: "A",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A large GF-friendly menu with unusually strong protocols: dedicated GF processes, dedicated air fryers, and a separate GF pizza oven at some locations. Not a fully dedicated kitchen, but among the best fast-casual options.",
    menu: [
      { name: "GF pizza", status: "gf-menu-item", note: "Separate oven at some locations." },
      { name: "Grain / veggie bowls", status: "gf-modifiable" },
      { name: "Salads", status: "gf-modifiable" },
      { name: "GF burger / bun", status: "gf-menu-item" },
    ],
    orderingTips: [
      "Tell staff it's an allergy order; a manager often handles it.",
      "Ask whether your location uses a separate GF pizza oven.",
      "Dedicated air fryers reduce fried-item risk.",
    ],
  },
  {
    id: "jasonsdeli",
    name: "Jason's Deli",
    domain: "jasonsdeli.com",
    segment: "fast-casual",
    category: "Deli / Sandwiches",
    baseGrade: "B",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Offers a gluten-sensitive menu plus GF bread, a big salad bar, and three GF soups. Each location keeps a color-coded (purple) gluten-sensitive prep kit with separate boards and toasting trays — not a dedicated GF kitchen.",
    menu: [
      { name: "GF bread sandwich (build-your-own)", status: "gf-menu-item" },
      { name: "Salad bar", status: "naturally-gf", note: "Avoid croutons/pasta." },
      { name: "Tomato basil / veggie / tortilla soup", status: "gf-menu-item" },
      { name: "Regular breads", status: "risky" },
    ],
    orderingTips: [
      "Ask for the gluten-sensitive prep kit (purple utensils).",
      "Order GF bread with fresh gloves and a clean toasting tray.",
      "Stick to naturally-GF salad bar items and the GF soups.",
    ],
  },
  {
    id: "peiwei",
    name: "Pei Wei",
    domain: "peiwei.com",
    segment: "fast-casual",
    category: "Asian",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Marks GF-able dishes and uses gluten-free soy sauce across all dishes, preparing GF orders in a separate area with a dedicated GF wok. Shared kitchen, but the dedicated-pan policy is strong for Asian fast-casual.",
    menu: [
      { name: "GF-tagged stir-fries (request GF prep)", status: "gf-modifiable", note: "Cooked in a dedicated GF pan." },
      { name: "Chicken & broccoli", status: "gf-modifiable" },
      { name: "Steamed white rice", status: "naturally-gf" },
      { name: "Fried / battered items", status: "risky" },
    ],
    orderingTips: [
      "Tell the cashier you want it prepared gluten-free.",
      "House soy sauce is GF; avoid fried/battered items.",
      "Choose steamed rice over noodles.",
    ],
  },
  {
    id: "pollotropical",
    name: "Pollo Tropical",
    domain: "pollotropical.com",
    segment: "fast-casual",
    category: "Caribbean / Chicken",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Most of the menu is gluten-free by ingredient if you avoid the wraps: grilled chicken, rice, beans, and build-your-own TropiChop bowls. Not a dedicated facility; better for sensitivity than strict celiac without care.",
    menu: [
      { name: "Grilled chicken breast", status: "naturally-gf" },
      { name: "TropiChop bowl (rice + chicken)", status: "gf-modifiable" },
      { name: "White/yellow rice & beans", status: "naturally-gf" },
      { name: "Wraps", status: "risky" },
    ],
    orderingTips: [
      "Build a TropiChop bowl with grilled chicken; skip wraps.",
      "Check the website GF listing before ordering.",
      "Ask about cross-contact — not a dedicated GF kitchen.",
    ],
  },
  {
    id: "bostonmarket",
    name: "Boston Market",
    domain: "bostonmarket.com",
    segment: "fast-casual",
    category: "Rotisserie / Home-style",
    baseGrade: "B",
    dedicatedFryer: true,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Rotisserie chicken and turkey breast are gluten-free, with GF poultry gravy and many naturally-GF sides (mashed potatoes, corn, green beans, steamed veg). Steam-table/shared prep, but the rotisserie core is a reliable base.",
    menu: [
      { name: "Rotisserie chicken", status: "naturally-gf" },
      { name: "Turkey breast", status: "naturally-gf" },
      { name: "GF poultry gravy", status: "gf-menu-item" },
      { name: "Mashed potatoes / steamed veg / corn", status: "naturally-gf" },
      { name: "Cornbread / mac & cheese", status: "risky" },
    ],
    orderingTips: [
      "Stick to rotisserie chicken/turkey and naturally-GF sides.",
      "The poultry gravy is GF; skip cornbread and stuffing.",
      "Ask for fresh utensils at the steam table.",
    ],
  },
  {
    id: "torchystacos",
    name: "Torchy's Tacos",
    domain: "torchystacos.com",
    segment: "fast-casual",
    category: "Tacos / Tex-Mex",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A laminated 'gluten-conscious' menu with clearly labeled options; corn tortillas, chips, and grilled-protein tacos are GF by ingredient. Watch the queso (wheat thickener), fried items, and shared prep with flour tortillas.",
    menu: [
      { name: "Grilled protein tacos (corn tortilla)", status: "gf-modifiable" },
      { name: "Corn tortillas & chips", status: "naturally-gf" },
      { name: "Breakfast tacos (corn)", status: "gf-modifiable" },
      { name: "Queso / fried fillings", status: "risky", note: "Queso uses a wheat-flour thickener." },
    ],
    orderingTips: [
      "Ask for the gluten-conscious menu.",
      "Choose grilled proteins on corn tortillas.",
      "Skip the queso and request fresh gloves.",
    ],
  },
  {
    id: "tropicalsmoothiecafe",
    name: "Tropical Smoothie Cafe",
    domain: "tropicalsmoothiecafe.com",
    segment: "cafe",
    category: "Smoothies / Cafe",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Most fruit smoothies and açaí/pitaya bowls are naturally gluten-free, and salads/wraps can be ordered as bowls. Labels items 'gluten-friendly' but shares prep — a sensitivity-level option.",
    menu: [
      { name: "Fruit smoothies", status: "naturally-gf" },
      { name: "Açaí / pitaya bowl", status: "naturally-gf" },
      { name: "Salads (no croutons, GF dressing)", status: "gf-modifiable" },
      { name: "Flatbreads / wraps", status: "risky" },
    ],
    orderingTips: [
      "Stick to fruit smoothies and açaí/pitaya bowls.",
      "Order wraps as a bowl, no tortilla.",
      "Shared prep; flag celiac for fresh gloves.",
    ],
  },
  {
    id: "caferio",
    name: "Cafe Rio",
    domain: "caferio.com",
    segment: "fast-casual",
    category: "Mexican",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Lists around 10 gluten-friendly options: salads (no tortilla bowl), grilled chicken, cilantro-lime rice, corn tortillas, and flan. Not certified GF, with mixed cross-contamination reports on the assembly line.",
    menu: [
      { name: "Salad (no flour tortilla bowl)", status: "gf-modifiable" },
      { name: "Grilled chicken", status: "naturally-gf" },
      { name: "Cilantro-lime rice", status: "naturally-gf" },
      { name: "Flour tortilla / burrito", status: "risky" },
    ],
    orderingTips: [
      "Skip the flour tortilla bowl; order a salad or corn tortillas.",
      "Ask for fresh gloves and clean utensils on the line.",
      "Not certified GF; mixed cross-contact reports.",
    ],
  },
  {
    id: "mcalistersdeli",
    name: "McAlister's Deli",
    domain: "mcalistersdeli.com",
    segment: "fast-casual",
    category: "Deli / Sandwiches",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Offers GF bread at some locations plus GF-able salads, baked-potato 'spuds', and select soups. No dedicated GF menu and shared prep — a reasonable sensitivity option, not celiac-safe without confirming.",
    menu: [
      { name: "Grilled chicken spud (baked potato)", status: "gf-modifiable" },
      { name: "Italian chopped salad (no croutons)", status: "gf-modifiable" },
      { name: "GF bread sandwich", status: "gf-menu-item", note: "Availability varies by location." },
      { name: "Croutons / regular bread", status: "risky" },
    ],
    orderingTips: [
      "Ask whether your location stocks GF bread.",
      "Default to a spud or salad without croutons.",
      "Request fresh gloves and a clean prep surface.",
    ],
  },
  {
    id: "genghisgrill",
    name: "Genghis Grill",
    domain: "genghisgrill.com",
    segment: "fast-casual",
    category: "Mongolian / Stir-fry",
    baseGrade: "C",
    dedicatedFryer: true,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A build-your-own Mongolian stir-fry where several sauces and rice noodles are GF, and staff will clean the shared grill before cooking your bowl. The big shared flat-top is the main risk.",
    menu: [
      { name: "Build-your-own bowl (GF sauce + rice)", status: "gf-modifiable", note: "Mongo BBQ, sweet-n-sour, mango BBQ are GF." },
      { name: "GF rice noodles", status: "gf-menu-item" },
      { name: "Fresh veggies & meats", status: "naturally-gf" },
      { name: "Most other sauces", status: "risky", note: "Many contain soy/wheat." },
    ],
    orderingTips: [
      "Ask for the GF item list and a freshly cleaned grill section.",
      "Use only confirmed-GF sauces.",
      "Choose rice or GF rice noodles over regular noodles.",
    ],
  },

  // ───────────────── SIT-DOWN · ITALIAN / PIZZA (more) ─────────────────
  {
    id: "maggianos",
    name: "Maggiano's Little Italy",
    domain: "maggianos.com",
    segment: "sit-down",
    category: "Italian",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A dedicated GF menu that swaps in GF fusilli on most classic pasta dishes, plus GF desserts. Chefs are allergen-trained and often visit the table, but pasta shares a kitchen and cookware.",
    menu: [
      { name: "GF pasta (substituted in most dishes)", status: "gf-menu-item" },
      { name: "Chicken parmesan (GF prep)", status: "gf-modifiable" },
      { name: "Flourless chocolate cake", status: "gf-menu-item" },
      { name: "House salads", status: "gf-modifiable", note: "No croutons; confirm dressing." },
    ],
    orderingTips: [
      "Ask for the GF menu and the GF pasta substitution.",
      "Tell your server you have celiac so the chef is alerted.",
      "Ask about a fresh pot of water; skip the bread service.",
    ],
  },
  {
    id: "mellowmushroom",
    name: "Mellow Mushroom",
    domain: "mellowmushroom.com",
    segment: "pizza",
    category: "Pizza",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Uses a certified GF crust made in a dedicated facility and preps it at a separate station with changed gloves and a screen. Widely praised crust, but GF pizzas bake in the shared oven, so safety varies by location.",
    menu: [
      { name: "GF pizza (certified crust)", status: "gf-menu-item", note: "Small size; dedicated-facility crust." },
      { name: "Build-your-own GF pizza", status: "gf-menu-item" },
      { name: "Salads (no croutons)", status: "gf-modifiable" },
      { name: "Hoagies / pretzels", status: "risky" },
    ],
    orderingTips: [
      "Order the certified GF crust and confirm separate prep.",
      "Ask them to change gloves and use the GF cutter/screen.",
      "GF pies share the oven; ask about location protocol.",
    ],
  },
  {
    id: "bertuccis",
    name: "Bertucci's",
    domain: "bertuccis.com",
    segment: "pizza",
    category: "Italian / Pizza",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A gluten-sensitive menu and a cauliflower-based GF pizza crust baked on a designated sheet and cut with a color-coded GF-only cutter. Shared commercial kitchen, but the pizza protocol is better than most.",
    menu: [
      { name: "GF cauliflower-crust pizza", status: "gf-menu-item" },
      { name: "GF cauliflower flatbread", status: "gf-menu-item" },
      { name: "Salads", status: "gf-modifiable" },
      { name: "Regular pasta / brick-oven bread", status: "risky" },
    ],
    orderingTips: [
      "Look for the 'G' icon and say it's gluten-sensitive.",
      "Order the GF cauliflower crust; confirm the color-coded cutter.",
      "Request GF flatbread instead of focaccia.",
    ],
  },

  // ───────────────── SIT-DOWN · SEAFOOD / AMERICAN / ASIAN (more) ─────────────────
  {
    id: "bonefishgrill",
    name: "Bonefish Grill",
    domain: "bonefishgrill.com",
    segment: "sit-down",
    category: "Seafood",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A gluten-friendly menu built around wood-grilled fish plus GF sides like mashed potatoes and jasmine rice. The chain explicitly warns against fried items (shared fryer), but grilled proteins are a solid choice.",
    menu: [
      { name: "Wood-grilled salmon / sea bass / trout", status: "gf-menu-item" },
      { name: "Grilled shrimp skewer", status: "gf-menu-item" },
      { name: "Garlic whipped mashed potatoes", status: "naturally-gf" },
      { name: "Any fried item (Bang Bang Shrimp)", status: "risky", note: "Shared fryer; chain advises against." },
    ],
    orderingTips: [
      "Request the gluten-friendly/allergen menu.",
      "Choose wood-grilled fish; avoid all fried items.",
      "Tell the server it's a celiac order for clean grill prep.",
    ],
  },
  {
    id: "benihana",
    name: "Benihana",
    domain: "benihana.com",
    segment: "sit-down",
    category: "Japanese / Hibachi",
    baseGrade: "B",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "Keeps gluten-free soy sauce on hand and publishes a fairly full gluten-sensitive menu of hibachi proteins, rice, and vegetables. The big risk is the communal teppanyaki grill plus regular soy sauce.",
    menu: [
      { name: "Hibachi steak / chicken / shrimp (GF soy)", status: "gf-modifiable", note: "Request GF soy sauce." },
      { name: "Hibachi vegetables", status: "gf-modifiable" },
      { name: "Plain steamed rice", status: "naturally-gf" },
      { name: "Gyoza / wings / fried rice", status: "risky", note: "Contain wheat / regular soy." },
    ],
    orderingTips: [
      "Insist on gluten-free soy sauce for everything.",
      "Ask the chef to clean the grill and cook your order first.",
      "Avoid gyoza, wings, tempura, and miso soup.",
    ],
  },
  {
    id: "cheddars",
    name: "Cheddar's Scratch Kitchen",
    domain: "cheddars.com",
    segment: "sit-down",
    category: "American",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "A gluten-sensitive menu with ~26 options including grilled proteins and naturally-GF sides (baked potato, broccoli, green beans). Items are still made in a shared kitchen; grill/fryer items carry extra risk.",
    menu: [
      { name: "Grilled steak / chicken / salmon", status: "gf-modifiable" },
      { name: "Baked potato / broccoli / green beans", status: "naturally-gf" },
      { name: "Plain rice", status: "naturally-gf" },
      { name: "Onion rings / breaded items / mac & cheese", status: "risky" },
    ],
    orderingTips: [
      "Request the gluten-sensitive menu and add the allergy to the ticket.",
      "Choose grilled proteins with naturally-GF sides.",
      "Avoid fryer and grill-shared breaded items.",
    ],
  },
  {
    id: "chuys",
    name: "Chuy's",
    domain: "chuys.com",
    segment: "sit-down",
    category: "Tex-Mex",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: true,
    hasGfMenu: true,
    summary:
      "GF and vegetarian menus are available on request (not online), and many enchiladas and tacos can be made GF with corn tortillas. But corn/flour tortillas share a griddle, chips fry alongside breaded shrimp, and meat is beer-marinated.",
    menu: [
      { name: "Corn-tortilla enchiladas / tacos", status: "gf-modifiable", note: "Request non-marinated meat." },
      { name: "Roasted chicken", status: "gf-modifiable" },
      { name: "Creamy jalapeño dip", status: "naturally-gf" },
      { name: "Chips / flour tortillas / beer-marinated meat", status: "risky" },
    ],
    orderingTips: [
      "Ask a manager for the GF menu (not online).",
      "Order corn tortillas and non-beer-marinated meat.",
      "Skip the chips (shared fryer with breaded shrimp).",
    ],
  },
  {
    id: "rubytuesday",
    name: "Ruby Tuesday",
    domain: "ruby-tuesday.com",
    segment: "sit-down",
    category: "American",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "An interactive online allergen filter surfaces many naturally-GF items — grilled steaks, salmon, chicken, steamed veggies, baked potatoes, salad bar — plus an optional GF bun. Signature biscuits aren't modifiable and cross-contact risk is high.",
    menu: [
      { name: "Grilled steak / salmon / chicken", status: "gf-modifiable" },
      { name: "Salad bar (no croutons)", status: "gf-modifiable" },
      { name: "Baked potato / steamed vegetables", status: "naturally-gf" },
      { name: "GF bun (burgers)", status: "gf-menu-item" },
      { name: "Garlic cheese biscuits", status: "risky" },
    ],
    orderingTips: [
      "Use the online allergen filter to confirm GF items.",
      "Order grilled proteins with naturally-GF sides; skip biscuits.",
      "Tell staff it's celiac for cross-contact precautions.",
    ],
  },
  {
    id: "elpolloloco",
    name: "El Pollo Loco",
    domain: "elpolloloco.com",
    segment: "fast-food",
    category: "Mexican / Chicken",
    baseGrade: "B",
    dedicatedFryer: true,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "The core is naturally gluten-free: citrus fire-grilled chicken, rice, beans, salsas, and many bowls. Shared kitchen without dedicated GF utensils, but the flame-grilled model means lots of safe-by-ingredient choices.",
    menu: [
      { name: "Fire-grilled chicken (all cuts)", status: "naturally-gf" },
      { name: "Beans & rice", status: "naturally-gf" },
      { name: "Avocado chicken bowl (no tortilla)", status: "gf-modifiable" },
      { name: "Corn tortillas", status: "naturally-gf" },
      { name: "Flour tortillas / burritos", status: "risky" },
    ],
    orderingTips: [
      "Order flame-grilled chicken with rice/beans and corn tortillas.",
      "Build a bowl with no flour tortilla.",
      "Ask for fresh gloves and a clean serving vessel.",
    ],
  },
  {
    id: "habitburger",
    name: "The Habit Burger Grill",
    domain: "habitburger.com",
    segment: "fast-food",
    category: "Burgers",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: true,
    summary:
      "Publishes a celiac/GF reference but offers only lettuce wraps (no GF bun), so a Charburger 'protein style' is the main path. Fries share a fryer with breaded items — a sensitivity-level choice.",
    menu: [
      { name: "Charburger protein style (lettuce wrap)", status: "gf-modifiable" },
      { name: "Salads (no croutons)", status: "gf-modifiable" },
      { name: "Fries / onion rings / crispy chicken", status: "risky", note: "Shared fryer." },
    ],
    orderingTips: [
      "Order Charburger protein style (lettuce wrap).",
      "Avoid fries and all fried items.",
      "Ask for fresh gloves and clean prep.",
    ],
  },
  {
    id: "smashburger",
    name: "Smashburger",
    domain: "smashburger.com",
    segment: "fast-casual",
    category: "Burgers",
    baseGrade: "C",
    dedicatedFryer: false,
    crossContaminationProtocol: false,
    hasGfMenu: false,
    summary:
      "Stocks Udi's gluten-free buns and lettuce wraps and will grill the bun separately if asked; most (but not all) locations use dedicated fry oil. Shared prep with no formal celiac program — confirm the fryer at your store.",
    menu: [
      { name: "Burger on Udi's GF bun", status: "gf-menu-item" },
      { name: "Lettuce-wrap burger", status: "gf-modifiable" },
      { name: "Fries", status: "risky", note: "Dedicated oil at most but not all locations." },
      { name: "Crispy chicken / onion rings", status: "risky" },
    ],
    orderingTips: [
      "Ask for the Udi's GF bun grilled separately.",
      "Confirm your location has dedicated fry oil before ordering fries.",
      "Request fresh gloves and a clean spatula.",
    ],
  },
];
