import type { Recipe } from "./types";

/**
 * Extended gluten-free recipe library (generated batch). Spread into
 * SEED_RECIPES so browse/fallback have broad cuisine + meal-type coverage.
 */
export const SEED_RECIPES_EXTRA: Recipe[] = [
  {
    id: "seed-caprese-frittata",
    title: "Caprese Frittata",
    cuisine: "italian",
    description: "A fluffy baked egg frittata loaded with fresh mozzarella, cherry tomatoes, and basil.",
    time: 30,
    servings: 4,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "large eggs", quantity: "8" },
      { name: "cherry tomatoes, halved", quantity: "1 cup" },
      { name: "fresh mozzarella, torn", quantity: "4 oz" },
      { name: "fresh basil leaves", quantity: "1/4 cup" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "1/2 tsp" },
      { name: "black pepper", quantity: "1/4 tsp" },
    ],
    steps: [
      "Preheat oven to 375F.",
      "Whisk eggs with salt and pepper in a bowl.",
      "Heat olive oil in an oven-safe skillet over medium heat and add cherry tomatoes, cooking 2 minutes.",
      "Pour in the eggs and scatter mozzarella on top.",
      "Cook 3 minutes until edges set, then transfer to the oven and bake 12 minutes until puffed and golden.",
      "Top with fresh basil and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-french-buckwheat-galettes-with-ham-and-egg",
    title: "French Buckwheat Galettes with Ham and Egg",
    cuisine: "french",
    description: "Savory naturally gluten-free buckwheat crepes folded around ham, cheese, and a runny egg.",
    time: 45,
    servings: 4,
    difficulty: "medium",
    mealType: "breakfast",
    ingredients: [
      { name: "buckwheat flour", quantity: "1 1/4 cups" },
      { name: "water", quantity: "1 1/2 cups" },
      { name: "large eggs", quantity: "5" },
      { name: "salt", quantity: "3/4 tsp" },
      { name: "butter", quantity: "3 tbsp" },
      { name: "sliced ham", quantity: "4 slices" },
      { name: "grated Gruyere cheese", quantity: "1 cup" },
    ],
    steps: [
      "Whisk buckwheat flour, water, 1 egg, and salt into a smooth batter and rest 30 minutes.",
      "Heat a little butter in a nonstick skillet over medium heat.",
      "Pour in a ladle of batter and swirl to coat the pan; cook 2 minutes.",
      "Lay a slice of ham and a handful of Gruyere in the center, then crack an egg on top.",
      "Fold the four edges inward to form a square, leaving the yolk exposed.",
      "Cook 3 more minutes until the cheese melts and the egg white sets, then repeat for remaining galettes.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-greek-yogurt-honey-walnut-bowl",
    title: "Greek Yogurt Honey Walnut Bowl",
    cuisine: "mediterranean",
    description: "A creamy Greek yogurt bowl topped with honey, walnuts, and fresh figs.",
    time: 5,
    servings: 2,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "plain Greek yogurt", quantity: "2 cups" },
      { name: "honey", quantity: "2 tbsp" },
      { name: "walnuts, chopped", quantity: "1/3 cup" },
      { name: "fresh figs, quartered", quantity: "4" },
      { name: "ground cinnamon", quantity: "1/4 tsp" },
    ],
    steps: [
      "Divide the Greek yogurt between two bowls.",
      "Drizzle honey over each bowl.",
      "Top with chopped walnuts and quartered figs.",
      "Sprinkle with cinnamon and serve immediately.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-sheet-pan-sweet-potato-hash-and-eggs",
    title: "Sheet-Pan Sweet Potato Hash and Eggs",
    cuisine: "american",
    description: "Crispy roasted sweet potatoes and peppers with eggs baked right on the pan.",
    time: 40,
    servings: 4,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "sweet potatoes, diced", quantity: "2 large" },
      { name: "red bell pepper, diced", quantity: "1" },
      { name: "red onion, diced", quantity: "1" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "smoked paprika", quantity: "1 tsp" },
      { name: "large eggs", quantity: "4" },
      { name: "salt", quantity: "1 tsp" },
      { name: "black pepper", quantity: "1/2 tsp" },
    ],
    steps: [
      "Preheat oven to 425F.",
      "Toss sweet potatoes, bell pepper, and onion with olive oil, paprika, salt, and pepper on a sheet pan.",
      "Roast 25 minutes, stirring once, until tender and browned.",
      "Make four wells in the hash and crack an egg into each.",
      "Return to the oven and bake 7 minutes until egg whites are set.",
      "Serve hot.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-tuscan-white-bean-and-kale-soup",
    title: "Tuscan White Bean and Kale Soup",
    cuisine: "italian",
    description: "A hearty rustic soup of cannellini beans, kale, and tomatoes in a garlic broth.",
    time: 40,
    servings: 6,
    difficulty: "easy",
    mealType: "soup",
    ingredients: [
      { name: "cannellini beans, drained", quantity: "two 15-oz cans" },
      { name: "kale, chopped", quantity: "4 cups" },
      { name: "diced tomatoes", quantity: "one 14-oz can" },
      { name: "garlic cloves, minced", quantity: "4" },
      { name: "yellow onion, diced", quantity: "1" },
      { name: "carrots, diced", quantity: "2" },
      { name: "gluten-free vegetable broth", quantity: "6 cups" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "1 tsp" },
    ],
    steps: [
      "Heat olive oil in a large pot over medium heat and saute onion and carrots 5 minutes.",
      "Add garlic and cook 1 minute until fragrant.",
      "Stir in tomatoes, beans, and broth, then bring to a simmer.",
      "Simmer 15 minutes to meld flavors.",
      "Add kale and cook 5 more minutes until wilted.",
      "Season with salt and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-french-carrot-ginger-soup",
    title: "French Carrot Ginger Soup",
    cuisine: "french",
    description: "A silky blended carrot soup brightened with fresh ginger and a touch of cream.",
    time: 40,
    servings: 4,
    difficulty: "easy",
    mealType: "soup",
    ingredients: [
      { name: "carrots, sliced", quantity: "2 lbs" },
      { name: "yellow onion, diced", quantity: "1" },
      { name: "fresh ginger, grated", quantity: "1 tbsp" },
      { name: "gluten-free vegetable broth", quantity: "4 cups" },
      { name: "heavy cream", quantity: "1/4 cup" },
      { name: "butter", quantity: "2 tbsp" },
      { name: "salt", quantity: "1 tsp" },
    ],
    steps: [
      "Melt butter in a pot over medium heat and cook onion 5 minutes until soft.",
      "Add carrots and ginger and cook 3 minutes.",
      "Pour in broth and bring to a boil, then simmer 20 minutes until carrots are tender.",
      "Blend until smooth using an immersion blender.",
      "Stir in cream and salt, warm through, and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-mediterranean-lemon-chicken-orzo-soup",
    title: "Mediterranean Lemon Chicken Orzo Soup",
    cuisine: "mediterranean",
    description: "A bright lemony soup with shredded chicken and gluten-free orzo in herbed broth.",
    time: 45,
    servings: 6,
    difficulty: "medium",
    mealType: "soup",
    ingredients: [
      { name: "boneless chicken thighs", quantity: "1 lb" },
      { name: "gluten-free orzo", quantity: "1 cup" },
      { name: "gluten-free chicken broth", quantity: "8 cups" },
      { name: "carrots, diced", quantity: "2" },
      { name: "celery, diced", quantity: "2 stalks" },
      { name: "onion, diced", quantity: "1" },
      { name: "lemon juice", quantity: "1/4 cup" },
      { name: "fresh dill, chopped", quantity: "2 tbsp" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "1 tsp" },
    ],
    steps: [
      "Heat olive oil in a large pot and saute onion, carrots, and celery 5 minutes.",
      "Add chicken broth and chicken thighs, bring to a boil, then simmer 20 minutes.",
      "Remove chicken, shred it, and return it to the pot.",
      "Stir in gluten-free orzo and cook 8 minutes until tender.",
      "Add lemon juice, dill, and salt.",
      "Serve hot.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-classic-american-chicken-and-rice-soup",
    title: "Classic American Chicken and Rice Soup",
    cuisine: "american",
    description: "A comforting brothy soup with tender chicken, vegetables, and white rice.",
    time: 50,
    servings: 6,
    difficulty: "easy",
    mealType: "soup",
    ingredients: [
      { name: "boneless chicken breast", quantity: "1 lb" },
      { name: "long-grain white rice", quantity: "3/4 cup" },
      { name: "gluten-free chicken broth", quantity: "8 cups" },
      { name: "carrots, sliced", quantity: "3" },
      { name: "celery, sliced", quantity: "3 stalks" },
      { name: "onion, diced", quantity: "1" },
      { name: "garlic cloves, minced", quantity: "2" },
      { name: "fresh thyme", quantity: "1 tsp" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "salt", quantity: "1 tsp" },
    ],
    steps: [
      "Heat olive oil in a large pot and saute onion, carrots, and celery 6 minutes.",
      "Add garlic and thyme and cook 1 minute.",
      "Pour in broth and add chicken breast; bring to a boil and simmer 18 minutes.",
      "Remove chicken, shred, and return to pot.",
      "Add rice and simmer 18 minutes until tender.",
      "Season with salt and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-risotto-alla-milanese",
    title: "Risotto alla Milanese",
    cuisine: "italian",
    description: "A creamy saffron-infused Arborio rice risotto finished with Parmesan.",
    time: 45,
    servings: 4,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "Arborio rice", quantity: "1 1/2 cups" },
      { name: "saffron threads", quantity: "1 pinch" },
      { name: "gluten-free chicken broth", quantity: "5 cups" },
      { name: "dry white wine", quantity: "1/2 cup" },
      { name: "shallot, minced", quantity: "1" },
      { name: "butter", quantity: "3 tbsp" },
      { name: "grated Parmesan", quantity: "3/4 cup" },
      { name: "salt", quantity: "1/2 tsp" },
    ],
    steps: [
      "Warm the broth in a saucepan and steep the saffron in it.",
      "Melt 2 tbsp butter in a wide pan and saute shallot 3 minutes.",
      "Add Arborio rice and toast 2 minutes until edges turn translucent.",
      "Pour in white wine and stir until absorbed.",
      "Add warm saffron broth one ladle at a time, stirring constantly, until rice is creamy and al dente, about 20 minutes.",
      "Stir in remaining butter, Parmesan, and salt, then serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-provencal-herb-roasted-salmon-with-ratatouille",
    title: "Provencal Herb-Roasted Salmon with Ratatouille",
    cuisine: "french",
    description: "Roasted salmon fillets served over a colorful stewed ratatouille of summer vegetables.",
    time: 55,
    servings: 4,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "salmon fillets", quantity: "4 (6 oz each)" },
      { name: "eggplant, diced", quantity: "1" },
      { name: "zucchini, diced", quantity: "2" },
      { name: "red bell pepper, diced", quantity: "1" },
      { name: "diced tomatoes", quantity: "one 14-oz can" },
      { name: "garlic cloves, minced", quantity: "3" },
      { name: "herbes de Provence", quantity: "2 tsp" },
      { name: "olive oil", quantity: "4 tbsp" },
      { name: "salt", quantity: "1 tsp" },
    ],
    steps: [
      "Heat 3 tbsp olive oil in a large pan and cook eggplant, zucchini, and bell pepper 8 minutes.",
      "Add garlic, tomatoes, 1 tsp herbes de Provence, and salt; simmer 20 minutes until thick.",
      "Meanwhile, preheat oven to 400F.",
      "Rub salmon with remaining oil, herbes de Provence, and salt, and place on a lined sheet pan.",
      "Roast salmon 12 minutes until just cooked through.",
      "Serve salmon over the ratatouille.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-mediterranean-stuffed-bell-peppers",
    title: "Mediterranean Stuffed Bell Peppers",
    cuisine: "mediterranean",
    description: "Bell peppers baked with a savory filling of rice, chickpeas, herbs, and feta.",
    time: 60,
    servings: 4,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "bell peppers, tops removed", quantity: "4" },
      { name: "cooked white rice", quantity: "2 cups" },
      { name: "chickpeas, drained", quantity: "one 15-oz can" },
      { name: "crumbled feta", quantity: "3/4 cup" },
      { name: "cherry tomatoes, halved", quantity: "1 cup" },
      { name: "fresh parsley, chopped", quantity: "1/4 cup" },
      { name: "garlic cloves, minced", quantity: "2" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "dried oregano", quantity: "1 tsp" },
      { name: "salt", quantity: "3/4 tsp" },
    ],
    steps: [
      "Preheat oven to 375F.",
      "In a bowl, combine rice, chickpeas, feta, tomatoes, parsley, garlic, oregano, 2 tbsp olive oil, and salt.",
      "Stuff the mixture into the hollowed bell peppers.",
      "Stand the peppers in a baking dish and drizzle with remaining oil.",
      "Cover with foil and bake 35 minutes.",
      "Uncover and bake 10 more minutes until peppers are tender, then serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-american-bbq-pulled-chicken-stuffed-potatoes",
    title: "American BBQ Pulled Chicken Stuffed Potatoes",
    cuisine: "american",
    description: "Fluffy baked potatoes loaded with smoky barbecue pulled chicken and scallions.",
    time: 75,
    servings: 4,
    difficulty: "easy",
    mealType: "dinner",
    ingredients: [
      { name: "russet potatoes", quantity: "4 large" },
      { name: "boneless chicken breast", quantity: "1 lb" },
      { name: "gluten-free barbecue sauce", quantity: "3/4 cup" },
      { name: "shredded cheddar", quantity: "1 cup" },
      { name: "scallions, sliced", quantity: "3" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt", quantity: "1/2 tsp" },
    ],
    steps: [
      "Preheat oven to 425F.",
      "Rub potatoes with olive oil and salt, then bake 60 minutes until tender.",
      "Meanwhile, poach chicken in simmering water 18 minutes, then shred.",
      "Toss the shredded chicken with gluten-free barbecue sauce.",
      "Split each baked potato and fill with the BBQ chicken.",
      "Top with cheddar and scallions and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-zucchini-noodle-aglio-e-olio",
    title: "Zucchini Noodle Aglio e Olio",
    cuisine: "italian",
    description: "Spiralized zucchini tossed in garlic, olive oil, and chili flakes for a light pasta-free lunch.",
    time: 20,
    servings: 2,
    difficulty: "easy",
    mealType: "lunch",
    ingredients: [
      { name: "zucchini, spiralized", quantity: "4" },
      { name: "garlic cloves, thinly sliced", quantity: "4" },
      { name: "olive oil", quantity: "1/4 cup" },
      { name: "red pepper flakes", quantity: "1/2 tsp" },
      { name: "fresh parsley, chopped", quantity: "3 tbsp" },
      { name: "lemon juice", quantity: "1 tbsp" },
      { name: "salt", quantity: "1/2 tsp" },
    ],
    steps: [
      "Heat olive oil in a large skillet over medium-low heat.",
      "Add garlic and red pepper flakes and cook gently 2 minutes until fragrant but not browned.",
      "Add the zucchini noodles and toss 3 minutes until just tender.",
      "Remove from heat and stir in parsley, lemon juice, and salt.",
      "Serve immediately.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-nicoise-salad",
    title: "Nicoise Salad",
    cuisine: "french",
    description: "A classic composed salad of tuna, green beans, potatoes, eggs, and olives with vinaigrette.",
    time: 35,
    servings: 4,
    difficulty: "medium",
    mealType: "lunch",
    ingredients: [
      { name: "canned tuna in oil, drained", quantity: "two 5-oz cans" },
      { name: "baby potatoes", quantity: "1 lb" },
      { name: "green beans, trimmed", quantity: "8 oz" },
      { name: "large eggs", quantity: "4" },
      { name: "cherry tomatoes, halved", quantity: "1 cup" },
      { name: "Nicoise olives", quantity: "1/3 cup" },
      { name: "Dijon mustard", quantity: "1 tbsp" },
      { name: "red wine vinegar", quantity: "2 tbsp" },
      { name: "olive oil", quantity: "1/3 cup" },
      { name: "salt", quantity: "1/2 tsp" },
    ],
    steps: [
      "Boil potatoes 15 minutes until tender, then halve.",
      "Blanch green beans in boiling water 3 minutes, then plunge into ice water.",
      "Boil eggs 9 minutes, cool, peel, and quarter.",
      "Whisk Dijon, vinegar, olive oil, and salt into a vinaigrette.",
      "Arrange potatoes, green beans, tomatoes, eggs, olives, and tuna on a platter.",
      "Drizzle with vinaigrette and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-mediterranean-chickpea-quinoa-salad",
    title: "Mediterranean Chickpea Quinoa Salad",
    cuisine: "mediterranean",
    description: "A fresh herb-packed quinoa salad with chickpeas, cucumber, tomato, and lemon.",
    time: 30,
    servings: 4,
    difficulty: "easy",
    mealType: "lunch",
    ingredients: [
      { name: "quinoa", quantity: "1 cup" },
      { name: "chickpeas, drained", quantity: "one 15-oz can" },
      { name: "cucumber, diced", quantity: "1" },
      { name: "cherry tomatoes, halved", quantity: "1 cup" },
      { name: "fresh parsley, chopped", quantity: "1 cup" },
      { name: "fresh mint, chopped", quantity: "1/4 cup" },
      { name: "lemon juice", quantity: "3 tbsp" },
      { name: "olive oil", quantity: "1/4 cup" },
      { name: "salt", quantity: "3/4 tsp" },
    ],
    steps: [
      "Rinse quinoa and cook in 2 cups water 15 minutes until fluffy, then cool.",
      "In a large bowl, combine chickpeas, cucumber, tomatoes, parsley, and mint.",
      "Add the cooled quinoa.",
      "Whisk lemon juice, olive oil, and salt and pour over the salad.",
      "Toss well and serve chilled or at room temperature.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-american-cobb-salad",
    title: "American Cobb Salad",
    cuisine: "american",
    description: "A loaded chopped salad with chicken, bacon, egg, avocado, and blue cheese.",
    time: 30,
    servings: 4,
    difficulty: "easy",
    mealType: "lunch",
    ingredients: [
      { name: "romaine lettuce, chopped", quantity: "1 large head" },
      { name: "cooked chicken breast, diced", quantity: "2 cups" },
      { name: "bacon, cooked and crumbled", quantity: "6 slices" },
      { name: "hard-boiled eggs, chopped", quantity: "4" },
      { name: "avocado, diced", quantity: "2" },
      { name: "cherry tomatoes, halved", quantity: "1 cup" },
      { name: "blue cheese, crumbled", quantity: "1/2 cup" },
      { name: "red wine vinaigrette (gluten-free)", quantity: "1/3 cup" },
    ],
    steps: [
      "Spread chopped romaine across a large platter.",
      "Arrange chicken, bacon, eggs, avocado, tomatoes, and blue cheese in rows on top.",
      "Drizzle with gluten-free red wine vinaigrette.",
      "Toss at the table and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-parmesan-roasted-asparagus",
    title: "Parmesan Roasted Asparagus",
    cuisine: "italian",
    description: "Tender roasted asparagus spears topped with crisp golden Parmesan.",
    time: 20,
    servings: 4,
    difficulty: "easy",
    mealType: "side",
    ingredients: [
      { name: "asparagus, trimmed", quantity: "1 lb" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "grated Parmesan", quantity: "1/3 cup" },
      { name: "garlic powder", quantity: "1/2 tsp" },
      { name: "salt", quantity: "1/2 tsp" },
      { name: "black pepper", quantity: "1/4 tsp" },
    ],
    steps: [
      "Preheat oven to 425F.",
      "Toss asparagus with olive oil, garlic powder, salt, and pepper on a sheet pan.",
      "Sprinkle Parmesan over the spears.",
      "Roast 12 minutes until tender and the cheese is golden.",
      "Serve warm.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-french-potato-gratin-dauphinois",
    title: "French Potato Gratin Dauphinois",
    cuisine: "french",
    description: "Thinly sliced potatoes baked in garlic cream until tender and golden.",
    time: 75,
    servings: 6,
    difficulty: "medium",
    mealType: "side",
    ingredients: [
      { name: "russet potatoes, thinly sliced", quantity: "2 lbs" },
      { name: "heavy cream", quantity: "2 cups" },
      { name: "garlic cloves, halved", quantity: "2" },
      { name: "grated Gruyere", quantity: "1 cup" },
      { name: "butter", quantity: "1 tbsp" },
      { name: "nutmeg", quantity: "1/4 tsp" },
      { name: "salt", quantity: "1 tsp" },
    ],
    steps: [
      "Preheat oven to 375F and rub a baking dish with the cut garlic, then butter it.",
      "Layer potato slices in the dish, seasoning each layer with salt and nutmeg.",
      "Pour cream evenly over the potatoes.",
      "Top with Gruyere.",
      "Bake 60 minutes until bubbling and golden.",
      "Rest 10 minutes before serving.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-lemon-garlic-roasted-mediterranean-vegetables",
    title: "Lemon Garlic Roasted Mediterranean Vegetables",
    cuisine: "mediterranean",
    description: "A colorful medley of roasted zucchini, peppers, and red onion with lemon and herbs.",
    time: 40,
    servings: 6,
    difficulty: "easy",
    mealType: "side",
    ingredients: [
      { name: "zucchini, sliced", quantity: "2" },
      { name: "red bell peppers, chunked", quantity: "2" },
      { name: "red onion, wedged", quantity: "1" },
      { name: "cherry tomatoes", quantity: "1 cup" },
      { name: "garlic cloves, minced", quantity: "3" },
      { name: "lemon juice", quantity: "2 tbsp" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "dried oregano", quantity: "1 tsp" },
      { name: "salt", quantity: "3/4 tsp" },
    ],
    steps: [
      "Preheat oven to 425F.",
      "Toss all vegetables with garlic, olive oil, oregano, and salt on a large sheet pan.",
      "Spread in a single layer and roast 25 minutes, stirring once.",
      "Drizzle with lemon juice and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-crispy-smashed-garlic-potatoes",
    title: "Crispy Smashed Garlic Potatoes",
    cuisine: "american",
    description: "Boiled baby potatoes smashed and roasted until crispy with garlic and herbs.",
    time: 50,
    servings: 4,
    difficulty: "easy",
    mealType: "side",
    ingredients: [
      { name: "baby potatoes", quantity: "1.5 lbs" },
      { name: "olive oil", quantity: "1/4 cup" },
      { name: "garlic powder", quantity: "1 tsp" },
      { name: "fresh rosemary, chopped", quantity: "1 tbsp" },
      { name: "salt", quantity: "1 tsp" },
      { name: "black pepper", quantity: "1/2 tsp" },
    ],
    steps: [
      "Boil baby potatoes 18 minutes until fork-tender, then drain.",
      "Preheat oven to 450F.",
      "Arrange potatoes on an oiled sheet pan and smash each flat with a glass.",
      "Drizzle with olive oil and sprinkle with garlic powder, rosemary, salt, and pepper.",
      "Roast 25 minutes until crispy and golden, then serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-italian-marinated-olives-and-almonds",
    title: "Italian Marinated Olives and Almonds",
    cuisine: "italian",
    description: "Warm citrus-and-herb marinated olives tossed with toasted almonds.",
    time: 15,
    servings: 6,
    difficulty: "easy",
    mealType: "snack",
    ingredients: [
      { name: "mixed olives", quantity: "2 cups" },
      { name: "raw almonds", quantity: "1 cup" },
      { name: "olive oil", quantity: "1/4 cup" },
      { name: "orange zest", quantity: "1 tbsp" },
      { name: "garlic clove, smashed", quantity: "1" },
      { name: "fresh rosemary", quantity: "1 sprig" },
      { name: "red pepper flakes", quantity: "1/4 tsp" },
    ],
    steps: [
      "Toast almonds in a dry skillet over medium heat 4 minutes until fragrant.",
      "Add olive oil, garlic, rosemary, orange zest, and red pepper flakes and warm 1 minute.",
      "Add the olives and toss to coat, warming 3 minutes.",
      "Transfer to a bowl and serve warm.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-mediterranean-roasted-red-pepper-hummus-with-veggies",
    title: "Mediterranean Roasted Red Pepper Hummus with Veggies",
    cuisine: "mediterranean",
    description: "A creamy roasted red pepper hummus served with crunchy fresh vegetable dippers.",
    time: 15,
    servings: 6,
    difficulty: "easy",
    mealType: "snack",
    ingredients: [
      { name: "chickpeas, drained", quantity: "one 15-oz can" },
      { name: "roasted red peppers", quantity: "1/2 cup" },
      { name: "tahini", quantity: "1/4 cup" },
      { name: "lemon juice", quantity: "3 tbsp" },
      { name: "garlic clove", quantity: "1" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "ground cumin", quantity: "1/2 tsp" },
      { name: "salt", quantity: "3/4 tsp" },
      { name: "assorted raw vegetables for dipping", quantity: "4 cups" },
    ],
    steps: [
      "Combine chickpeas, roasted red peppers, tahini, lemon juice, garlic, cumin, and salt in a food processor.",
      "Blend while drizzling in olive oil until smooth, adding a splash of water if needed.",
      "Transfer to a bowl and drizzle with a little extra olive oil.",
      "Serve with assorted raw vegetables for dipping.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-huevos-rancheros-on-crispy-corn-tortillas",
    title: "Huevos Rancheros on Crispy Corn Tortillas",
    cuisine: "mexican",
    description: "Fried eggs over crisp corn tortillas smothered in a smoky ranchero salsa.",
    time: 30,
    servings: 2,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "corn tortillas", quantity: "4" },
      { name: "eggs", quantity: "4" },
      { name: "canned diced tomatoes", quantity: "1 cup" },
      { name: "white onion, chopped", quantity: "1/2" },
      { name: "jalapeno, minced", quantity: "1" },
      { name: "garlic cloves, minced", quantity: "2" },
      { name: "ground cumin", quantity: "1/2 tsp" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "queso fresco, crumbled", quantity: "1/4 cup" },
      { name: "fresh cilantro, chopped", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" },
    ],
    steps: [
      "Heat 1 tbsp oil in a skillet and saute onion, jalapeno, and garlic until soft, about 4 minutes.",
      "Add tomatoes, cumin, and salt; simmer 8 minutes until thickened into a salsa.",
      "In a separate pan, fry the corn tortillas in remaining oil until lightly crisp, about 1 minute per side; set aside.",
      "Fry the eggs in the same pan to desired doneness.",
      "Place two tortillas per plate, top with fried eggs, spoon ranchero salsa over, and finish with queso fresco and cilantro.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-korean-tofu-scramble-rice-bowl",
    title: "Korean Tofu Scramble Rice Bowl",
    cuisine: "asian",
    description: "A savory tofu scramble with gochujang and scallions served over warm rice.",
    time: 25,
    servings: 2,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "firm tofu, drained", quantity: "14 oz" },
      { name: "tamari (GF soy sauce)", quantity: "2 tbsp" },
      { name: "gochujang (verify GF)", quantity: "1 tbsp" },
      { name: "toasted sesame oil", quantity: "1 tbsp" },
      { name: "garlic cloves, minced", quantity: "2" },
      { name: "scallions, sliced", quantity: "3" },
      { name: "cooked white rice", quantity: "2 cups" },
      { name: "toasted sesame seeds", quantity: "1 tbsp" },
      { name: "neutral oil", quantity: "1 tbsp" },
    ],
    steps: [
      "Crumble the tofu with your hands into bite-size pieces.",
      "Heat neutral oil in a skillet over medium heat and add garlic, cooking 30 seconds.",
      "Add crumbled tofu and cook 5 minutes, stirring, until lightly golden.",
      "Stir in tamari, gochujang, and sesame oil; cook another 3 minutes.",
      "Divide rice between bowls, top with tofu scramble, and garnish with scallions and sesame seeds.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-masala-vegetable-frittata",
    title: "Masala Vegetable Frittata",
    cuisine: "indian",
    description: "An Indian-spiced baked egg frittata loaded with peppers, peas, and onion.",
    time: 35,
    servings: 4,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "eggs", quantity: "8" },
      { name: "milk", quantity: "1/4 cup" },
      { name: "red bell pepper, diced", quantity: "1" },
      { name: "red onion, diced", quantity: "1" },
      { name: "frozen peas", quantity: "1/2 cup" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "ground turmeric", quantity: "1/2 tsp" },
      { name: "green chili, minced", quantity: "1" },
      { name: "fresh cilantro, chopped", quantity: "3 tbsp" },
      { name: "ghee", quantity: "2 tbsp" },
      { name: "salt", quantity: "to taste" },
    ],
    steps: [
      "Preheat oven to 375F.",
      "Heat ghee in an ovenproof skillet and saute onion, bell pepper, and chili until soft, about 6 minutes.",
      "Stir in peas, garam masala, turmeric, and salt; cook 2 minutes.",
      "Whisk eggs with milk, then pour over the vegetables and stir gently.",
      "Cook on the stovetop 2 minutes, then transfer to the oven and bake 15 minutes until set.",
      "Sprinkle with cilantro, slice, and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-sweet-potato-and-black-bean-breakfast-tacos",
    title: "Sweet Potato and Black Bean Breakfast Tacos",
    cuisine: "mexican",
    description: "Warm corn tortillas filled with spiced roasted sweet potato and black beans.",
    time: 40,
    servings: 3,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "corn tortillas", quantity: "6" },
      { name: "sweet potato, diced", quantity: "1 large" },
      { name: "canned black beans, drained", quantity: "1 cup" },
      { name: "chili powder", quantity: "1 tsp" },
      { name: "ground cumin", quantity: "1/2 tsp" },
      { name: "smoked paprika", quantity: "1/2 tsp" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "avocado, sliced", quantity: "1" },
      { name: "lime", quantity: "1" },
      { name: "fresh cilantro", quantity: "1/4 cup" },
      { name: "salt", quantity: "to taste" },
    ],
    steps: [
      "Preheat oven to 425F.",
      "Toss sweet potato with oil, chili powder, cumin, paprika, and salt; roast 25 minutes until tender.",
      "Warm the black beans in a small pot with a pinch of salt.",
      "Heat the corn tortillas over a flame or in a dry skillet until pliable.",
      "Fill tortillas with sweet potato and beans, top with avocado, cilantro, and a squeeze of lime.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-american-buckwheat-blueberry-pancakes",
    title: "American Buckwheat Blueberry Pancakes",
    cuisine: "american",
    description: "Fluffy naturally gluten-free buckwheat pancakes studded with fresh blueberries.",
    time: 25,
    servings: 4,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "buckwheat flour", quantity: "1 1/2 cups" },
      { name: "baking powder", quantity: "2 tsp" },
      { name: "sugar", quantity: "2 tbsp" },
      { name: "salt", quantity: "1/4 tsp" },
      { name: "eggs", quantity: "2" },
      { name: "milk", quantity: "1 1/4 cups" },
      { name: "melted butter", quantity: "3 tbsp" },
      { name: "fresh blueberries", quantity: "1 cup" },
      { name: "maple syrup", quantity: "for serving" },
    ],
    steps: [
      "Whisk buckwheat flour, baking powder, sugar, and salt in a bowl.",
      "In another bowl whisk eggs, milk, and melted butter.",
      "Combine wet and dry ingredients until just mixed, then fold in blueberries.",
      "Heat a greased griddle over medium and pour 1/4-cup portions of batter.",
      "Cook until bubbles form, about 2 minutes, flip, and cook 1 more minute.",
      "Serve warm with maple syrup.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-chicken-tortilla-soup",
    title: "Chicken Tortilla Soup",
    cuisine: "mexican",
    description: "A brothy tomato-chili soup with shredded chicken and crispy corn tortilla strips.",
    time: 45,
    servings: 6,
    difficulty: "medium",
    mealType: "soup",
    ingredients: [
      { name: "boneless chicken breasts", quantity: "1 lb" },
      { name: "corn tortillas", quantity: "4" },
      { name: "canned crushed tomatoes", quantity: "1 1/2 cups" },
      { name: "GF chicken broth", quantity: "6 cups" },
      { name: "white onion, diced", quantity: "1" },
      { name: "garlic cloves, minced", quantity: "3" },
      { name: "chipotle in adobo, minced", quantity: "1" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "lime", quantity: "1" },
      { name: "fresh cilantro", quantity: "1/4 cup" },
      { name: "salt", quantity: "to taste" },
    ],
    steps: [
      "Cut tortillas into thin strips and fry in 2 tbsp oil until crisp; drain and set aside.",
      "In the same pot heat remaining oil and saute onion and garlic until soft, 5 minutes.",
      "Add cumin, chipotle, and tomatoes; cook 3 minutes.",
      "Pour in broth, add chicken breasts, and simmer 20 minutes until chicken is cooked.",
      "Remove chicken, shred, and return to the pot; season with salt.",
      "Serve topped with tortilla strips, cilantro, and a squeeze of lime.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-thai-coconut-curry-rice-noodle-soup",
    title: "Thai Coconut Curry Rice Noodle Soup",
    cuisine: "asian",
    description: "A fragrant coconut curry broth with rice noodles, shrimp, and fresh herbs.",
    time: 35,
    servings: 4,
    difficulty: "medium",
    mealType: "soup",
    ingredients: [
      { name: "rice noodles", quantity: "8 oz" },
      { name: "shrimp, peeled", quantity: "1 lb" },
      { name: "coconut milk", quantity: "1 can (14 oz)" },
      { name: "GF red curry paste", quantity: "3 tbsp" },
      { name: "GF chicken or vegetable broth", quantity: "4 cups" },
      { name: "tamari (GF soy sauce)", quantity: "2 tbsp" },
      { name: "fish sauce (verify GF)", quantity: "1 tbsp" },
      { name: "lime", quantity: "2" },
      { name: "fresh basil", quantity: "1/4 cup" },
      { name: "bean sprouts", quantity: "1 cup" },
      { name: "neutral oil", quantity: "1 tbsp" },
    ],
    steps: [
      "Soak rice noodles in warm water per package directions, then drain.",
      "Heat oil in a pot and fry the curry paste for 1 minute until fragrant.",
      "Add coconut milk and broth; bring to a gentle simmer.",
      "Stir in tamari and fish sauce, then add shrimp and cook 3 minutes until pink.",
      "Divide noodles among bowls and ladle the hot soup over.",
      "Top with bean sprouts, basil, and a squeeze of lime.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-indian-red-lentil-dal-soup",
    title: "Indian Red Lentil Dal Soup",
    cuisine: "indian",
    description: "A comforting spiced red lentil soup finished with a sizzling cumin tempering.",
    time: 40,
    servings: 4,
    difficulty: "easy",
    mealType: "soup",
    ingredients: [
      { name: "red lentils, rinsed", quantity: "1 cup" },
      { name: "water", quantity: "4 cups" },
      { name: "ground turmeric", quantity: "1/2 tsp" },
      { name: "tomato, chopped", quantity: "1" },
      { name: "onion, chopped", quantity: "1" },
      { name: "garlic cloves, minced", quantity: "3" },
      { name: "fresh ginger, grated", quantity: "1 tbsp" },
      { name: "cumin seeds", quantity: "1 tsp" },
      { name: "dried red chili", quantity: "1" },
      { name: "coconut oil", quantity: "2 tbsp" },
      { name: "fresh cilantro", quantity: "3 tbsp" },
      { name: "salt", quantity: "to taste" },
    ],
    steps: [
      "Combine lentils, water, turmeric, and half the onion in a pot; simmer 20 minutes until soft.",
      "Stir in tomato and salt; cook 5 more minutes, then lightly mash.",
      "Heat coconut oil in a small pan and add cumin seeds, dried chili, garlic, ginger, and remaining onion.",
      "Fry the tempering until golden and fragrant, about 3 minutes.",
      "Pour the sizzling tempering into the dal and stir.",
      "Garnish with cilantro and serve hot.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-loaded-nachos-with-refried-beans",
    title: "Loaded Nachos with Refried Beans",
    cuisine: "mexican",
    description: "Crispy corn tortilla chips piled with refried beans, cheese, and pico de gallo.",
    time: 25,
    servings: 4,
    difficulty: "easy",
    mealType: "snack",
    ingredients: [
      { name: "corn tortilla chips", quantity: "8 oz" },
      { name: "canned refried beans", quantity: "1 cup" },
      { name: "shredded cheddar cheese", quantity: "1 1/2 cups" },
      { name: "tomato, diced", quantity: "1" },
      { name: "white onion, diced", quantity: "1/4" },
      { name: "jalapeno, sliced", quantity: "1" },
      { name: "fresh cilantro", quantity: "2 tbsp" },
      { name: "lime", quantity: "1/2" },
      { name: "sour cream", quantity: "1/4 cup" },
    ],
    steps: [
      "Preheat oven to 400F.",
      "Spread tortilla chips on a baking sheet.",
      "Dot with spoonfuls of warmed refried beans and sprinkle cheese over the top.",
      "Bake 8 minutes until the cheese melts.",
      "Combine tomato, onion, cilantro, and lime to make a quick pico de gallo.",
      "Top the nachos with pico, jalapeno slices, and dollops of sour cream.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-edamame-with-sesame-and-chili",
    title: "Edamame with Sesame and Chili",
    cuisine: "asian",
    description: "Steamed edamame tossed in a quick toasted sesame and chili-tamari glaze.",
    time: 15,
    servings: 4,
    difficulty: "easy",
    mealType: "snack",
    ingredients: [
      { name: "frozen edamame in pods", quantity: "1 lb" },
      { name: "tamari (GF soy sauce)", quantity: "1 tbsp" },
      { name: "toasted sesame oil", quantity: "1 tbsp" },
      { name: "chili flakes", quantity: "1/2 tsp" },
      { name: "garlic clove, grated", quantity: "1" },
      { name: "toasted sesame seeds", quantity: "1 tbsp" },
      { name: "flaky sea salt", quantity: "to taste" },
    ],
    steps: [
      "Steam or boil edamame pods for 5 minutes until bright green and tender.",
      "Drain well and transfer to a bowl.",
      "Whisk tamari, sesame oil, chili flakes, and garlic together.",
      "Toss the warm edamame with the glaze.",
      "Sprinkle with sesame seeds and flaky salt before serving.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-spiced-roasted-chickpeas",
    title: "Spiced Roasted Chickpeas",
    cuisine: "indian",
    description: "Crunchy oven-roasted chickpeas coated in warm Indian spices.",
    time: 45,
    servings: 4,
    difficulty: "easy",
    mealType: "snack",
    ingredients: [
      { name: "canned chickpeas, drained", quantity: "2 cups" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "garam masala", quantity: "1 tsp" },
      { name: "ground cumin", quantity: "1/2 tsp" },
      { name: "ground turmeric", quantity: "1/4 tsp" },
      { name: "cayenne pepper", quantity: "1/4 tsp" },
      { name: "salt", quantity: "1/2 tsp" },
    ],
    steps: [
      "Preheat oven to 400F.",
      "Pat chickpeas thoroughly dry with a towel.",
      "Toss chickpeas with oil, garam masala, cumin, turmeric, cayenne, and salt.",
      "Spread on a baking sheet in a single layer.",
      "Roast 35 minutes, shaking the pan halfway, until crisp.",
      "Cool slightly and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-carne-asada-tacos",
    title: "Carne Asada Tacos",
    cuisine: "mexican",
    description: "Marinated grilled flank steak served on warm corn tortillas with onion and cilantro.",
    time: 50,
    servings: 4,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "flank steak", quantity: "1.5 lb" },
      { name: "corn tortillas", quantity: "12" },
      { name: "orange juice", quantity: "1/4 cup" },
      { name: "lime juice", quantity: "1/4 cup" },
      { name: "garlic cloves, minced", quantity: "4" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "chili powder", quantity: "1 tsp" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "white onion, diced", quantity: "1" },
      { name: "fresh cilantro, chopped", quantity: "1/2 cup" },
      { name: "salt", quantity: "to taste" },
    ],
    steps: [
      "Whisk orange juice, lime juice, garlic, cumin, chili powder, oil, and salt for the marinade.",
      "Marinate the flank steak 30 minutes at room temperature.",
      "Heat a grill or grill pan to high and cook the steak 4 minutes per side for medium.",
      "Rest the steak 5 minutes, then slice thinly against the grain.",
      "Warm the corn tortillas over a flame until pliable.",
      "Fill tortillas with steak and top with diced onion and cilantro.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-kung-pao-chicken-with-tamari",
    title: "Kung Pao Chicken with Tamari",
    cuisine: "asian",
    description: "Stir-fried chicken with peanuts and dried chilies in a glossy tamari sauce.",
    time: 35,
    servings: 4,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "boneless chicken thighs, cubed", quantity: "1.5 lb" },
      { name: "tamari (GF soy sauce)", quantity: "3 tbsp" },
      { name: "GF hoisin sauce (verify GF)", quantity: "1 tbsp" },
      { name: "rice vinegar", quantity: "2 tbsp" },
      { name: "cornstarch", quantity: "1 tbsp" },
      { name: "dried red chilies", quantity: "8" },
      { name: "roasted unsalted peanuts", quantity: "1/2 cup" },
      { name: "garlic cloves, minced", quantity: "3" },
      { name: "fresh ginger, minced", quantity: "1 tbsp" },
      { name: "scallions, sliced", quantity: "4" },
      { name: "neutral oil", quantity: "3 tbsp" },
    ],
    steps: [
      "Toss chicken with 1 tbsp tamari and cornstarch; let sit 10 minutes.",
      "Whisk remaining tamari, hoisin, and rice vinegar for the sauce.",
      "Heat 2 tbsp oil in a wok over high heat and stir-fry chicken until browned, 5 minutes; remove.",
      "Add remaining oil, dried chilies, garlic, and ginger; stir-fry 30 seconds.",
      "Return chicken, add the sauce, and toss until glossy and coated.",
      "Stir in peanuts and scallions and serve over rice.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-chicken-tikka-masala",
    title: "Chicken Tikka Masala",
    cuisine: "indian",
    description: "Tender marinated chicken simmered in a creamy spiced tomato sauce.",
    time: 60,
    servings: 4,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "boneless chicken thighs, cubed", quantity: "1.5 lb" },
      { name: "plain yogurt", quantity: "1/2 cup" },
      { name: "garam masala", quantity: "2 tsp" },
      { name: "ground cumin", quantity: "1 tsp" },
      { name: "paprika", quantity: "1 tsp" },
      { name: "canned tomato puree", quantity: "1 1/2 cups" },
      { name: "heavy cream", quantity: "3/4 cup" },
      { name: "onion, finely chopped", quantity: "1" },
      { name: "garlic cloves, minced", quantity: "4" },
      { name: "fresh ginger, grated", quantity: "1 tbsp" },
      { name: "ghee", quantity: "3 tbsp" },
      { name: "fresh cilantro", quantity: "1/4 cup" },
      { name: "salt", quantity: "to taste" },
    ],
    steps: [
      "Marinate chicken in yogurt, 1 tsp garam masala, cumin, and paprika for 20 minutes.",
      "Heat ghee in a pan and sear the chicken until browned; remove and set aside.",
      "In the same pan saute onion, garlic, and ginger until golden, 6 minutes.",
      "Add tomato puree and remaining garam masala; simmer 10 minutes.",
      "Stir in cream, return chicken, and simmer 10 minutes until cooked through.",
      "Season with salt, garnish with cilantro, and serve with rice.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-bbq-pulled-pork-stuffed-sweet-potatoes",
    title: "BBQ Pulled Pork Stuffed Sweet Potatoes",
    cuisine: "american",
    description: "Roasted sweet potatoes loaded with tender GF barbecue pulled pork.",
    time: 90,
    servings: 4,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "pork shoulder", quantity: "2 lb" },
      { name: "sweet potatoes", quantity: "4" },
      { name: "GF barbecue sauce", quantity: "1 cup" },
      { name: "smoked paprika", quantity: "1 tsp" },
      { name: "garlic powder", quantity: "1 tsp" },
      { name: "onion powder", quantity: "1 tsp" },
      { name: "GF chicken broth", quantity: "1 cup" },
      { name: "scallions, sliced", quantity: "3" },
      { name: "salt", quantity: "to taste" },
    ],
    steps: [
      "Rub pork with paprika, garlic powder, onion powder, and salt.",
      "Place pork and broth in a covered pot and braise at 325F for about 3 hours until fork-tender.",
      "Roast sweet potatoes at 400F for 45 minutes until soft.",
      "Shred the pork and toss with GF barbecue sauce.",
      "Split the sweet potatoes open and fill with pulled pork.",
      "Top with scallions and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-shrimp-fried-rice-with-tamari",
    title: "Shrimp Fried Rice with Tamari",
    cuisine: "asian",
    description: "Wok-fried day-old rice with shrimp, egg, and vegetables in a tamari sauce.",
    time: 25,
    servings: 4,
    difficulty: "easy",
    mealType: "dinner",
    ingredients: [
      { name: "cooked cold rice", quantity: "4 cups" },
      { name: "shrimp, peeled", quantity: "1 lb" },
      { name: "eggs, beaten", quantity: "2" },
      { name: "frozen peas and carrots", quantity: "1 cup" },
      { name: "tamari (GF soy sauce)", quantity: "3 tbsp" },
      { name: "toasted sesame oil", quantity: "1 tbsp" },
      { name: "garlic cloves, minced", quantity: "3" },
      { name: "scallions, sliced", quantity: "4" },
      { name: "neutral oil", quantity: "3 tbsp" },
    ],
    steps: [
      "Heat 1 tbsp neutral oil in a wok and scramble the eggs; remove and set aside.",
      "Add another tbsp oil and cook the shrimp until pink, about 3 minutes; remove.",
      "Add remaining oil, garlic, and peas and carrots; stir-fry 2 minutes.",
      "Add the cold rice and stir-fry over high heat 4 minutes, breaking up clumps.",
      "Return shrimp and eggs, then add tamari and sesame oil; toss well.",
      "Stir in scallions and serve hot.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-classic-american-pot-roast",
    title: "Classic American Pot Roast",
    cuisine: "american",
    description: "Fork-tender braised beef chuck with carrots and potatoes in a savory gravy.",
    time: 210,
    servings: 6,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "beef chuck roast", quantity: "3 lb" },
      { name: "carrots, chunked", quantity: "4" },
      { name: "Yukon gold potatoes, halved", quantity: "1.5 lb" },
      { name: "onion, quartered", quantity: "1" },
      { name: "GF beef broth", quantity: "3 cups" },
      { name: "tomato paste", quantity: "2 tbsp" },
      { name: "garlic cloves", quantity: "4" },
      { name: "fresh thyme", quantity: "4 sprigs" },
      { name: "cornstarch", quantity: "2 tbsp" },
      { name: "olive oil", quantity: "2 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
    steps: [
      "Preheat oven to 325F and season the roast generously with salt and pepper.",
      "Sear the roast in olive oil in a Dutch oven until browned on all sides.",
      "Add broth, tomato paste, garlic, onion, and thyme; cover and braise 2.5 hours.",
      "Add carrots and potatoes and braise 45 more minutes until everything is tender.",
      "Remove the meat and vegetables; whisk cornstarch with a little water and stir into the liquid to thicken into gravy.",
      "Slice the roast and serve with vegetables and gravy.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-cilantro-lime-rice",
    title: "Cilantro Lime Rice",
    cuisine: "mexican",
    description: "Fluffy white rice brightened with lime juice and fresh cilantro.",
    time: 25,
    servings: 4,
    difficulty: "easy",
    mealType: "side",
    ingredients: [
      { name: "long-grain white rice", quantity: "1 cup" },
      { name: "water", quantity: "2 cups" },
      { name: "lime juice", quantity: "2 tbsp" },
      { name: "lime zest", quantity: "1 tsp" },
      { name: "fresh cilantro, chopped", quantity: "1/3 cup" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt", quantity: "1/2 tsp" },
    ],
    steps: [
      "Rinse the rice under cold water until the water runs clear.",
      "Combine rice, water, oil, and salt in a pot and bring to a boil.",
      "Reduce heat to low, cover, and simmer 18 minutes until water is absorbed.",
      "Remove from heat and let rest 5 minutes.",
      "Fluff with a fork and stir in lime juice, zest, and cilantro.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-garlic-sesame-bok-choy",
    title: "Garlic Sesame Bok Choy",
    cuisine: "asian",
    description: "Quick-seared baby bok choy in a garlicky tamari and sesame sauce.",
    time: 15,
    servings: 4,
    difficulty: "easy",
    mealType: "side",
    ingredients: [
      { name: "baby bok choy, halved", quantity: "1 lb" },
      { name: "tamari (GF soy sauce)", quantity: "2 tbsp" },
      { name: "toasted sesame oil", quantity: "1 tbsp" },
      { name: "garlic cloves, minced", quantity: "3" },
      { name: "fresh ginger, grated", quantity: "1 tsp" },
      { name: "toasted sesame seeds", quantity: "1 tbsp" },
      { name: "neutral oil", quantity: "1 tbsp" },
    ],
    steps: [
      "Heat neutral oil in a large skillet over high heat.",
      "Add bok choy cut-side down and sear 2 minutes until lightly charred.",
      "Add garlic and ginger and stir-fry 30 seconds.",
      "Pour in tamari and sesame oil and toss 1 minute until bok choy is just tender.",
      "Sprinkle with sesame seeds and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-jeera-cumin-basmati-rice",
    title: "Jeera Cumin Basmati Rice",
    cuisine: "indian",
    description: "Aromatic basmati rice tempered with whole cumin seeds and ghee.",
    time: 30,
    servings: 4,
    difficulty: "easy",
    mealType: "side",
    ingredients: [
      { name: "basmati rice", quantity: "1 cup" },
      { name: "water", quantity: "1 3/4 cups" },
      { name: "cumin seeds", quantity: "1 tsp" },
      { name: "ghee", quantity: "2 tbsp" },
      { name: "bay leaf", quantity: "1" },
      { name: "salt", quantity: "1/2 tsp" },
    ],
    steps: [
      "Rinse basmati rice and soak 15 minutes, then drain.",
      "Heat ghee in a pot and add cumin seeds and bay leaf; sizzle 30 seconds.",
      "Add the drained rice and toast 1 minute, stirring.",
      "Add water and salt and bring to a boil.",
      "Cover, reduce heat to low, and cook 15 minutes until water is absorbed.",
      "Rest 5 minutes, then fluff with a fork.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-mexican-street-corn-salad-esquites",
    title: "Mexican Street Corn Salad (Esquites)",
    cuisine: "mexican",
    description: "Charred corn tossed with lime, chili, cotija, and a creamy dressing.",
    time: 20,
    servings: 4,
    difficulty: "easy",
    mealType: "side",
    ingredients: [
      { name: "corn kernels", quantity: "4 cups" },
      { name: "mayonnaise", quantity: "3 tbsp" },
      { name: "cotija cheese, crumbled", quantity: "1/3 cup" },
      { name: "lime juice", quantity: "2 tbsp" },
      { name: "chili powder", quantity: "1 tsp" },
      { name: "fresh cilantro, chopped", quantity: "1/4 cup" },
      { name: "jalapeno, minced", quantity: "1" },
      { name: "olive oil", quantity: "1 tbsp" },
      { name: "salt", quantity: "to taste" },
    ],
    steps: [
      "Heat olive oil in a skillet over high heat and char the corn 6 minutes until spots blister.",
      "Transfer corn to a bowl and let cool slightly.",
      "Stir in mayonnaise, lime juice, chili powder, jalapeno, and salt.",
      "Fold in cotija cheese and cilantro.",
      "Serve warm or at room temperature.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-american-quinoa-power-lunch-bowl",
    title: "American Quinoa Power Lunch Bowl",
    cuisine: "american",
    description: "A hearty quinoa bowl with roasted vegetables, chickpeas, and lemon tahini dressing.",
    time: 40,
    servings: 3,
    difficulty: "easy",
    mealType: "lunch",
    ingredients: [
      { name: "quinoa", quantity: "1 cup" },
      { name: "water", quantity: "2 cups" },
      { name: "broccoli florets", quantity: "2 cups" },
      { name: "canned chickpeas, drained", quantity: "1 cup" },
      { name: "cherry tomatoes, halved", quantity: "1 cup" },
      { name: "tahini", quantity: "3 tbsp" },
      { name: "lemon juice", quantity: "2 tbsp" },
      { name: "garlic clove, grated", quantity: "1" },
      { name: "olive oil", quantity: "3 tbsp" },
      { name: "salt and pepper", quantity: "to taste" },
    ],
    steps: [
      "Rinse quinoa, combine with water and a pinch of salt, and simmer covered 15 minutes; fluff.",
      "Preheat oven to 425F and toss broccoli and chickpeas with 1 tbsp oil, salt, and pepper.",
      "Roast the broccoli and chickpeas 20 minutes until crisp-tender.",
      "Whisk tahini, lemon juice, garlic, remaining oil, and a splash of water into a dressing.",
      "Divide quinoa among bowls and top with roasted vegetables, chickpeas, and cherry tomatoes.",
      "Drizzle with lemon tahini dressing and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-lion-ribeye-steak",
    title: "Lion Ribeye Steak",
    cuisine: "american",
    description: "A simple seared ruminant ribeye seasoned with nothing but salt for the strictest carnivore approach.",
    time: 20,
    servings: 2,
    difficulty: "easy",
    mealType: "dinner",
    ingredients: [
      { name: "Beef ribeye steak", quantity: "2 steaks (12 oz each)" },
      { name: "Salt", quantity: "1 tsp" },
      { name: "Water", quantity: "1 tbsp" },
    ],
    steps: [
      "Pat the ribeye steaks dry and let them sit at room temperature for 30 minutes.",
      "Season both sides generously with salt.",
      "Heat a dry cast-iron skillet over high heat until smoking.",
      "Sear the steaks 3-4 minutes per side for medium-rare, rendering the fat against the pan edge.",
      "Rest 5 minutes before slicing and serving.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free, carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-slow-braised-lamb-shanks",
    title: "Slow-Braised Lamb Shanks",
    cuisine: "american",
    description: "Fall-off-the-bone lamb shanks braised in water with salt for a pure ruminant meal.",
    time: 210,
    servings: 4,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "Lamb shanks", quantity: "4 shanks (about 1 lb each)" },
      { name: "Salt", quantity: "2 tsp" },
      { name: "Water", quantity: "3 cups" },
    ],
    steps: [
      "Pat lamb shanks dry and season all over with salt.",
      "Sear the shanks in a dry hot Dutch oven until browned on all sides, using the rendering lamb fat.",
      "Add water to come halfway up the shanks and bring to a simmer.",
      "Cover and braise at 325F for 3 hours until the meat is tender and pulling from the bone.",
      "Reduce the cooking liquid on the stovetop and spoon over the shanks to serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free, carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-ground-bison-patties",
    title: "Ground Bison Patties",
    cuisine: "american",
    description: "Juicy pan-seared bison patties with just salt for a quick Lion-level meal.",
    time: 15,
    servings: 3,
    difficulty: "easy",
    mealType: "lunch",
    ingredients: [
      { name: "Ground bison", quantity: "1.5 lb" },
      { name: "Salt", quantity: "1.5 tsp" },
      { name: "Water", quantity: "2 tbsp" },
    ],
    steps: [
      "Gently mix the ground bison with salt, adding water to keep the lean meat moist.",
      "Form into 3 thick patties without overworking the meat.",
      "Heat a dry skillet over medium-high until hot.",
      "Cook patties 4-5 minutes per side until browned and cooked to your liking.",
      "Rest 3 minutes and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free, carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-crispy-skin-chicken-thighs-in-tallow",
    title: "Crispy Skin Chicken Thighs in Tallow",
    cuisine: "american",
    description: "Golden crispy-skinned chicken thighs cooked in beef tallow with simple dry spices.",
    time: 40,
    servings: 4,
    difficulty: "easy",
    mealType: "dinner",
    ingredients: [
      { name: "Bone-in skin-on chicken thighs", quantity: "8 thighs" },
      { name: "Beef tallow", quantity: "2 tbsp" },
      { name: "Salt", quantity: "1.5 tsp" },
      { name: "Black pepper", quantity: "1 tsp" },
      { name: "Garlic powder", quantity: "1 tsp" },
    ],
    steps: [
      "Pat chicken thighs very dry and season both sides with salt, pepper, and garlic powder.",
      "Melt beef tallow in a cold oven-safe skillet, then place thighs skin-side down.",
      "Cook over medium heat 12-15 minutes until skin is deeply golden and crisp.",
      "Flip the thighs and transfer skillet to a 400F oven for 15 minutes until cooked through.",
      "Rest briefly and serve with the rendered pan juices.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free, carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-pan-seared-salmon-with-crispy-skin",
    title: "Pan-Seared Salmon with Crispy Skin",
    cuisine: "american",
    description: "Buttery-textured salmon fillets seared in tallow with salt and pepper, no dairy.",
    time: 20,
    servings: 2,
    difficulty: "easy",
    mealType: "dinner",
    ingredients: [
      { name: "Salmon fillets, skin-on", quantity: "2 fillets (6 oz each)" },
      { name: "Beef tallow", quantity: "1 tbsp" },
      { name: "Salt", quantity: "1 tsp" },
      { name: "Black pepper", quantity: "0.5 tsp" },
    ],
    steps: [
      "Pat salmon dry and season the flesh and skin with salt and pepper.",
      "Heat tallow in a skillet over medium-high until shimmering.",
      "Place salmon skin-side down and press gently for 30 seconds to keep it flat.",
      "Cook 4-5 minutes until the skin is crisp, then flip and cook 2 minutes more.",
      "Rest 2 minutes and serve crisp-side up.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free, carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-bacon-wrapped-pork-tenderloin",
    title: "Bacon-Wrapped Pork Tenderloin",
    cuisine: "american",
    description: "Roasted pork tenderloin wrapped in bacon and seasoned with simple dry spices, no dairy.",
    time: 45,
    servings: 4,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "Pork tenderloin", quantity: "1 (1.25 lb)" },
      { name: "Bacon slices", quantity: "8 slices" },
      { name: "Salt", quantity: "1 tsp" },
      { name: "Black pepper", quantity: "1 tsp" },
      { name: "Smoked paprika", quantity: "1 tsp" },
    ],
    steps: [
      "Pat the tenderloin dry and season all over with salt, pepper, and smoked paprika.",
      "Wrap the tenderloin snugly with overlapping bacon slices, tucking the ends under.",
      "Sear in a hot dry oven-safe skillet, turning, until bacon begins to crisp.",
      "Transfer to a 400F oven and roast 20-25 minutes until the center reaches 145F.",
      "Rest 5 minutes, slice into medallions, and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free, carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-soft-scrambled-eggs-in-lard",
    title: "Soft Scrambled Eggs in Lard",
    cuisine: "american",
    description: "Silky scrambled eggs cooked low and slow in lard with salt and pepper, fully dairy-free.",
    time: 10,
    servings: 2,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "Eggs", quantity: "6 large" },
      { name: "Lard", quantity: "1 tbsp" },
      { name: "Salt", quantity: "0.5 tsp" },
      { name: "Black pepper", quantity: "0.25 tsp" },
    ],
    steps: [
      "Crack the eggs into a bowl and whisk until fully combined.",
      "Melt lard in a nonstick skillet over low heat.",
      "Pour in the eggs and stir constantly with a spatula, pushing curds gently.",
      "Remove from heat while still slightly glossy, as residual heat finishes cooking.",
      "Season with salt and pepper and serve immediately.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free, carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-garlic-pepper-shrimp-in-tallow",
    title: "Garlic-Pepper Shrimp in Tallow",
    cuisine: "american",
    description: "Quick-seared shrimp tossed in beef tallow with garlic powder and pepper, no dairy.",
    time: 15,
    servings: 3,
    difficulty: "easy",
    mealType: "dinner",
    ingredients: [
      { name: "Large shrimp, peeled and deveined", quantity: "1.5 lb" },
      { name: "Beef tallow", quantity: "2 tbsp" },
      { name: "Salt", quantity: "1 tsp" },
      { name: "Black pepper", quantity: "0.5 tsp" },
      { name: "Garlic powder", quantity: "1 tsp" },
    ],
    steps: [
      "Pat shrimp dry and toss with salt, pepper, and garlic powder.",
      "Melt tallow in a large skillet over medium-high heat.",
      "Add shrimp in a single layer and cook 2 minutes until pink underneath.",
      "Flip and cook 1-2 minutes more until just opaque and curled.",
      "Serve hot with the seasoned tallow spooned over.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free, carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-cheesy-beef-and-egg-skillet",
    title: "Cheesy Beef and Egg Skillet",
    cuisine: "american",
    description: "Ground beef and eggs baked with melted cheddar for a hearty dairy-level carnivore breakfast.",
    time: 25,
    servings: 4,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "Ground beef", quantity: "1 lb" },
      { name: "Eggs", quantity: "6 large" },
      { name: "Shredded cheddar cheese", quantity: "1 cup" },
      { name: "Butter", quantity: "1 tbsp" },
      { name: "Salt", quantity: "1 tsp" },
      { name: "Black pepper", quantity: "0.5 tsp" },
    ],
    steps: [
      "Melt butter in an oven-safe skillet and brown the ground beef with salt and pepper.",
      "Drain excess fat if needed and spread the beef into an even layer.",
      "Make six wells in the beef and crack an egg into each.",
      "Sprinkle the shredded cheddar over the top.",
      "Bake at 375F for 12-15 minutes until the whites set and cheese melts; serve hot.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-butter-basted-filet-mignon",
    title: "Butter-Basted Filet Mignon",
    cuisine: "american",
    description: "Tender filet mignon seared and basted in butter for a rich dairy-level carnivore dinner.",
    time: 25,
    servings: 2,
    difficulty: "medium",
    mealType: "dinner",
    ingredients: [
      { name: "Filet mignon steaks", quantity: "2 (8 oz each)" },
      { name: "Butter", quantity: "3 tbsp" },
      { name: "Salt", quantity: "1 tsp" },
      { name: "Black pepper", quantity: "0.5 tsp" },
    ],
    steps: [
      "Pat filets dry and season generously with salt and pepper.",
      "Sear in a hot dry skillet 3 minutes per side until a crust forms.",
      "Reduce heat to medium and add the butter to the pan.",
      "Tilt the skillet and spoon the foaming butter over the steaks for 1-2 minutes.",
      "Rest 5 minutes, then serve drizzled with the pan butter.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-three-cheese-baked-eggs",
    title: "Three-Cheese Baked Eggs",
    cuisine: "american",
    description: "Creamy baked eggs with cream and a trio of cheeses for an indulgent dairy carnivore start.",
    time: 25,
    servings: 4,
    difficulty: "easy",
    mealType: "breakfast",
    ingredients: [
      { name: "Eggs", quantity: "8 large" },
      { name: "Heavy cream", quantity: "1/3 cup" },
      { name: "Shredded mozzarella", quantity: "1/2 cup" },
      { name: "Grated parmesan", quantity: "1/4 cup" },
      { name: "Crumbled goat cheese", quantity: "1/4 cup" },
      { name: "Butter", quantity: "1 tbsp" },
      { name: "Salt", quantity: "0.75 tsp" },
    ],
    steps: [
      "Butter a baking dish and preheat the oven to 375F.",
      "Whisk eggs with cream and salt until smooth and pour into the dish.",
      "Scatter mozzarella, parmesan, and goat cheese evenly over the top.",
      "Bake 15-18 minutes until the center is just set and the top is golden.",
      "Cool 3 minutes before serving.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-cream-braised-short-ribs",
    title: "Cream-Braised Short Ribs",
    cuisine: "american",
    description: "Beef short ribs braised until tender in a buttery cream pan sauce for a dairy carnivore feast.",
    time: 195,
    servings: 4,
    difficulty: "advanced",
    mealType: "dinner",
    ingredients: [
      { name: "Bone-in beef short ribs", quantity: "4 lb" },
      { name: "Butter", quantity: "2 tbsp" },
      { name: "Heavy cream", quantity: "1 cup" },
      { name: "Salt", quantity: "2 tsp" },
      { name: "Black pepper", quantity: "1 tsp" },
      { name: "Water", quantity: "1 cup" },
    ],
    steps: [
      "Season short ribs all over with salt and pepper.",
      "Melt butter in a Dutch oven and sear the ribs on all sides until deeply browned.",
      "Add water, cover, and braise at 325F for 2.5 hours until fork-tender.",
      "Remove ribs, skim fat, and stir cream into the cooking liquid over medium heat.",
      "Simmer the sauce until slightly thickened, then return ribs to coat and serve.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — carnivore-friendly. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: true,
    source: "seed",
  },
  {
    id: "seed-flourless-chocolate-almond-cake",
    title: "Flourless Chocolate Almond Cake",
    cuisine: "dessert",
    description: "A dense, fudgy flourless chocolate cake made with almond flour and no wheat.",
    time: 50,
    servings: 8,
    difficulty: "medium",
    mealType: "dessert",
    ingredients: [
      { name: "Dark chocolate (gluten-free)", quantity: "8 oz" },
      { name: "Butter", quantity: "1/2 cup" },
      { name: "Almond flour", quantity: "1/2 cup" },
      { name: "Eggs", quantity: "4 large" },
      { name: "Granulated sugar", quantity: "3/4 cup" },
      { name: "Vanilla extract", quantity: "1 tsp" },
      { name: "Salt", quantity: "1/4 tsp" },
    ],
    steps: [
      "Preheat oven to 350F and line an 8-inch round pan with parchment.",
      "Melt the chocolate and butter together until smooth, then let cool slightly.",
      "Whisk in the sugar, eggs, vanilla, and salt until glossy.",
      "Fold in the almond flour until just combined and pour into the pan.",
      "Bake 28-32 minutes until the edges set but the center is slightly soft; cool before slicing.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-coconut-flour-brownies",
    title: "Coconut Flour Brownies",
    cuisine: "dessert",
    description: "Rich dairy-free brownies made with coconut flour and coconut oil for a fudgy gluten-free treat.",
    time: 40,
    servings: 12,
    difficulty: "easy",
    mealType: "dessert",
    ingredients: [
      { name: "Coconut flour", quantity: "1/2 cup" },
      { name: "Cocoa powder", quantity: "1/2 cup" },
      { name: "Coconut oil, melted", quantity: "1/2 cup" },
      { name: "Eggs", quantity: "4 large" },
      { name: "Maple syrup", quantity: "3/4 cup" },
      { name: "Vanilla extract", quantity: "1 tsp" },
      { name: "Baking soda", quantity: "1/4 tsp" },
      { name: "Salt", quantity: "1/4 tsp" },
    ],
    steps: [
      "Preheat oven to 350F and line an 8x8-inch pan with parchment.",
      "Whisk together the eggs, maple syrup, melted coconut oil, and vanilla.",
      "Sift in the coconut flour, cocoa powder, baking soda, and salt and stir until smooth.",
      "Let the batter rest 5 minutes to thicken, then spread into the pan.",
      "Bake 22-26 minutes until set at the edges; cool completely before cutting into squares.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-coconut-rice-pudding",
    title: "Coconut Rice Pudding",
    cuisine: "dessert",
    description: "A creamy dairy-free rice pudding simmered in coconut milk with cinnamon and vanilla.",
    time: 45,
    servings: 6,
    difficulty: "easy",
    mealType: "dessert",
    ingredients: [
      { name: "Arborio or jasmine rice", quantity: "3/4 cup" },
      { name: "Full-fat coconut milk", quantity: "2 cans (13.5 oz each)" },
      { name: "Maple syrup", quantity: "1/3 cup" },
      { name: "Vanilla extract", quantity: "1 tsp" },
      { name: "Ground cinnamon", quantity: "1/2 tsp" },
      { name: "Salt", quantity: "1/4 tsp" },
    ],
    steps: [
      "Combine rice, coconut milk, and salt in a saucepan and bring to a gentle simmer.",
      "Cook over low heat, stirring often, for 30-35 minutes until the rice is soft and creamy.",
      "Stir in the maple syrup, vanilla, and cinnamon.",
      "Simmer 3-5 minutes more until thickened to your liking.",
      "Serve warm or chilled, dusted with extra cinnamon.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-almond-flour-lemon-cookies",
    title: "Almond Flour Lemon Cookies",
    cuisine: "dessert",
    description: "Soft, chewy gluten-free lemon cookies made entirely with almond flour.",
    time: 30,
    servings: 18,
    difficulty: "easy",
    mealType: "dessert",
    ingredients: [
      { name: "Almond flour", quantity: "2.5 cups" },
      { name: "Maple syrup", quantity: "1/3 cup" },
      { name: "Coconut oil, melted", quantity: "1/4 cup" },
      { name: "Lemon zest", quantity: "2 tbsp" },
      { name: "Lemon juice", quantity: "2 tbsp" },
      { name: "Baking soda", quantity: "1/2 tsp" },
      { name: "Salt", quantity: "1/4 tsp" },
    ],
    steps: [
      "Preheat oven to 350F and line a baking sheet with parchment.",
      "Mix almond flour, baking soda, and salt in a bowl.",
      "Stir in the maple syrup, melted coconut oil, lemon zest, and lemon juice to form a dough.",
      "Scoop tablespoon-sized balls onto the sheet and flatten slightly.",
      "Bake 10-12 minutes until edges are golden; cool on the sheet before serving.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-rice-flour-vanilla-cupcakes",
    title: "Rice Flour Vanilla Cupcakes",
    cuisine: "dessert",
    description: "Light and fluffy gluten-free vanilla cupcakes made with rice flour and butter.",
    time: 35,
    servings: 12,
    difficulty: "medium",
    mealType: "dessert",
    ingredients: [
      { name: "White rice flour", quantity: "1.5 cups" },
      { name: "Tapioca starch", quantity: "1/4 cup" },
      { name: "Granulated sugar", quantity: "3/4 cup" },
      { name: "Butter, softened", quantity: "1/2 cup" },
      { name: "Eggs", quantity: "2 large" },
      { name: "Milk", quantity: "3/4 cup" },
      { name: "Baking powder", quantity: "2 tsp" },
      { name: "Vanilla extract", quantity: "2 tsp" },
      { name: "Salt", quantity: "1/4 tsp" },
    ],
    steps: [
      "Preheat oven to 350F and line a 12-cup muffin tin with liners.",
      "Cream the butter and sugar until light and fluffy.",
      "Beat in the eggs one at a time, then the vanilla.",
      "Whisk together rice flour, tapioca starch, baking powder, and salt, then add to the batter alternating with the milk.",
      "Divide into the liners and bake 18-20 minutes until a toothpick comes out clean; cool before frosting.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: false,
    carnivore: false,
    source: "seed",
  },
  {
    id: "seed-coconut-macaroons",
    title: "Coconut Macaroons",
    cuisine: "dessert",
    description: "Chewy golden coconut macaroons that are naturally gluten-free and dairy-free.",
    time: 35,
    servings: 20,
    difficulty: "easy",
    mealType: "dessert",
    ingredients: [
      { name: "Shredded unsweetened coconut", quantity: "3 cups" },
      { name: "Egg whites", quantity: "3 large" },
      { name: "Maple syrup", quantity: "1/2 cup" },
      { name: "Vanilla extract", quantity: "1 tsp" },
      { name: "Salt", quantity: "1/4 tsp" },
    ],
    steps: [
      "Preheat oven to 325F and line a baking sheet with parchment.",
      "Whisk the egg whites with salt until frothy.",
      "Stir in the maple syrup, vanilla, and shredded coconut until evenly moistened.",
      "Scoop tightly packed mounds onto the sheet using a spoon or small scoop.",
      "Bake 18-22 minutes until the tips and edges are golden; cool completely before removing.",
    ],
    glutenFreeNote: "Made with gluten-free ingredients as written — dairy-free. Always confirm packaged items (broth, sauces, tamari) are labeled gluten-free.",
    dairyFree: true,
    carnivore: false,
    source: "seed",
  },
];
