import { Header } from "@/components/Header";

export const metadata = { title: "Medical Disclaimer — Sift" };

export default function DisclaimerPage() {
  return (
    <div>
      <Header title="Medical Disclaimer" subtitle="Please read carefully" />
      <div className="prose-sift space-y-4 px-5 pb-10 pt-5 text-sm leading-relaxed text-gray-700">
        <p className="rounded-xl bg-clay-50 p-4 font-medium text-clay-800">
          Sift is an informational tool, not a medical device and not a
          substitute for professional medical or dietary advice.
        </p>

        <h2 className="font-display text-lg font-semibold text-grain-900">
          Not medical advice
        </h2>
        <p>
          Sift provides general information about gluten-free eating, recipes,
          products, and restaurants. It does not diagnose, treat, or prevent
          celiac disease, gluten sensitivity, allergies, or any other condition.
          Always consult a qualified healthcare professional or registered
          dietitian about your individual needs.
        </p>

        <h2 className="font-display text-lg font-semibold text-grain-900">
          Always verify ingredients yourself
        </h2>
        <p>
          Restaurant grades, product assessments, AI-generated recipes, and
          ordering guides are estimates based on available information and may
          be incomplete, out of date, or wrong. Manufacturers change recipes,
          and kitchens vary by location. Before eating anything, confirm
          gluten-free status by reading current labels and speaking with
          restaurant staff. If you have a severe allergy, treat all
          cross-contamination risks as potentially serious.
        </p>

        <h2 className="font-display text-lg font-semibold text-grain-900">
          AI-generated content
        </h2>
        <p>
          Some content is generated by AI and may contain errors. Use your own
          judgment and verify anything that affects your health.
        </p>

        <h2 className="font-display text-lg font-semibold text-grain-900">
          In an emergency
        </h2>
        <p>
          If you are experiencing a severe allergic reaction or medical
          emergency, contact your local emergency services immediately. Do not
          rely on this app.
        </p>

        <p className="text-xs text-gray-400">
          This template is a starting point and should be reviewed by a
          qualified professional before launch. Last updated: June 2026.
        </p>
      </div>
    </div>
  );
}
